version: '3'
services:
  mysql:
    image: mysql
    container_name: gluttex-db
    # restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
        - ./mysql/model.sql:/data/application/init.sql
        - ./data:/var/lib/mysql
        # - ./mysql/my.cnf:/etc/mysql/my.cnf  # Mount custom my.cnf
    networks:
      - gluttex-net
  gluttex-api:
    container_name: gluttex-api
    hostname: gluttex-api
    restart: always
    build:  server/.
    image: omarzos/gluttex-api
    ports:
      - ${API_PORT}:8000
    environment:
      - SQL_SCHEMA=${MYSQL_SCHEMA}
      - SQL_HOST=${MYSQL_HOST}
      - SQL_DATABASE=${MYSQL_DATABASE}
      - SQL_USER=${MYSQL_USER}
      - SQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - API_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - API_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - API_FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - API_INSTAGRAM_CLIENT_ID=${INSTAGRAM_CLIENT_ID}
      - API_INSTAGRAM_CLIENT_SECRET=${INSTAGRAM_CLIENT_SECRET}
      - API_SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - AUTH_SERVER_NAME=${AUTH_SERVER_NAME}
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_REGISTRATION_ENDPOINT=${AUTH_REGISTRATION_ENDPOINT}
      - AUTH_LOGIN_ENDPOINT=${AUTH_LOGIN_ENDPOINT}
      - AUTH_CHANGE_ENDPOINT=${AUTH_CHANGE_ENDPOINT}
    networks:
      - gluttex-net
    volumes:
      - ./server/:/code
  gluttex-auth:
    container_name: gluttex-auth
    hostname: gluttex-auth
    restart: always
    build:  auth_server/.
    image: omarzos/gluttex-auth
    ports:
      - ${AUTH_PORT}:8000
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - API_SECRET_KEY=${SECRET_KEY}
      - API_ALGORITHM=${ALGORITHM}
    networks:
      - gluttex-net
    volumes:
      - ./auth_server/:/code
      - ./auth_db/auth_db.db:/auth_db_data.db
volumes:
  data:
  auth_db:
networks:
  gluttex-net:
    name: gluttex-net
    driver: bridge