# version: '3.8'

# Dev mode only!!!

services:

  mysql:
    image: mysql
    container_name: gluttex-db
    restart: always
    command: --max_allowed_packet=256M --init-file /data/application/init.sql

    environment:
      MYSQL_DATABASE: ${SQL_DATABASE}
      # MYSQL_USER: ${SQL_USER}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      # MYSQL_PASSWORD: ${SQL_PASSWORD}
      
    ports:
      - ${SQL_PORT}:3306
    volumes:
      - ./mysql/model.sql:/data/application/init.sql
      - ./data:/var/lib/mysql
    networks:
      - gluttex-net
  gluttex-api:
    container_name: gluttex-api
    hostname: gluttex-api
    restart: unless-stopped
    build:
      context: ./api_server
      dockerfile: ./Dockerfile.dev
      args:
        - API_PORT=9000
    command: uvicorn server:app --host 0.0.0.0 --port 9000 --reload
    image: omarzos/gluttex-api
    ports:
      - 9000:9000
    environment:
      - API_PORT=9000
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_ROOT_PASSWORD}
      - SQL_PORT=3306
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_SERVER_NAME=${AUTH_SERVER_NAME}
      - AUTH_REGISTRATION_ENDPOINT=${AUTH_REGISTRATION_ENDPOINT}
      - AUTH_LOGIN_ENDPOINT=${AUTH_LOGIN_ENDPOINT}
      - ALGORITHM=${ALGORITHM}
      - API_SECRET_KEY=${SECRET_KEY}
      - FILE_UPLOAD_ENDPOINT=${FILE_UPLOAD_ENDPOINT}
      - FS_HOST=${FS_HOST}
      - FS_PORT=${FS_PORT}
    networks:
      - gluttex-net
    volumes:
      - ./api_server:/code
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M


networks:
  gluttex-net:
    name: gluttex-net
    driver: bridge