@startuml
skinparam componentStyle rectangle
skinparam shadowing false

package "Client Layer" {
  [gluttex-web]
  [gluttex-mobile]
}

package "Core Services" {
  [gluttex-api]
  [gluttex-auth]
  [gluttex-stream]
  [gluttex-fs]
}


package "Infrastructure" {
  [rabbitmq]
  [gluttex-db]
}

[gluttex-web] --> [gluttex-api] : REST / HTTPS
[gluttex-mobile] --> [gluttex-api] : REST / HTTPS

[gluttex-web] --> [gluttex-stream] : WebSocket / SSE
[gluttex-mobile] --> [gluttex-stream] : Realtime

[gluttex-api] --> [gluttex-auth]
[gluttex-api] --> [gluttex-db]
[gluttex-api] --> [gluttex-fs]
[gluttex-api] --> [rabbitmq]

[gluttex-stream] --> [rabbitmq]

@enduml
