FROM python:3.9-slim

# Copy the certificate files to the appropriate location in the container

WORKDIR /code
COPY certificates/cert.pem /etc/ssl/certs/cert.pem
COPY certificates/key.pem /etc/ssl/private/key.pem
COPY requirements.txt /


RUN pip3 install -r /requirements.txt --timeout=120

# CMD ["sh", "-c", "uvicorn server:app --host 0.0.0.0  --ssl-keyfile /etc/ssl/private/key.pem --ssl-certfile /etc/ssl/certs/cert.pem --port ${AUTH_PORT}"]
