-- MySQL Script generated by MySQL Workbench
-- Wed May 15 16:36:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gluttex` ;

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gluttex` DEFAULT CHARACTER SET utf8 ;
USE `gluttex` ;

-- -----------------------------------------------------
-- Table `gluttex`.`app_user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user_type` (
  `id_app_user_type` INT NOT NULL AUTO_INCREMENT,
  `app_user_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_app_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`person_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person_details` (
  `id_person_details` INT NOT NULL AUTO_INCREMENT,
  `person_first_name` VARCHAR(45) NULL,
  `person_last_name` VARCHAR(45) NULL,
  `person_birth_date` DATE NULL,
  `person_gender` VARCHAR(45) NULL,
  `person_nationality` VARCHAR(45) NULL,
  PRIMARY KEY (`id_person_details`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`blood_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`blood_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`blood_type` (
  `id_blood_type` INT NOT NULL AUTO_INCREMENT,
  `blood_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_blood_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`address` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(45) NULL,
  `address_city` VARCHAR(45) NULL,
  `address_postal_code` VARCHAR(45) NULL,
  `address_country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`location` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `location_latitude` DECIMAL(10,8) NULL,
  `location_longitude` DECIMAL(11,8) NULL,
  `location_name` VARCHAR(45) NULL,
  `location_address_id` INT NULL,
  PRIMARY KEY (`id_location`),
  INDEX `fk_location_1_idx` (`location_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_1`
    FOREIGN KEY (`location_address_id`)
    REFERENCES `gluttex`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `person_details_id` INT NULL,
  `person_blood_type_id` INT NULL,
  `person_location_id` INT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_1_idx` (`person_details_id` ASC) VISIBLE,
  INDEX `fk_person_2_idx` (`person_blood_type_id` ASC) VISIBLE,
  INDEX `fk_person_3_idx` (`person_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_1`
    FOREIGN KEY (`person_details_id`)
    REFERENCES `gluttex`.`person_details` (`id_person_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_2`
    FOREIGN KEY (`person_blood_type_id`)
    REFERENCES `gluttex`.`blood_type` (`id_blood_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_3`
    FOREIGN KEY (`person_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user` (
  `id_app_user` INT NOT NULL AUTO_INCREMENT,
  `app_user_name` VARCHAR(100) NULL,
  `app_user_password` VARCHAR(256) NULL,
  `app_user_person_id` INT NULL,
  `app_user_type_id` INT NULL,
  `app_user_preferences` TEXT NULL,
  `app_user_image` BLOB NULL,
  PRIMARY KEY (`id_app_user`),
  INDEX `fk_app_user_3_idx` (`app_user_person_id` ASC) VISIBLE,
  INDEX `fk_app_user_1_idx` (`app_user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_app_user_1`
    FOREIGN KEY (`app_user_type_id`)
    REFERENCES `gluttex`.`app_user_type` (`id_app_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_user_3`
    FOREIGN KEY (`app_user_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_provider_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider_type` (
  `id_product_provider_type` INT NOT NULL AUTO_INCREMENT,
  `product_provider_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product_provider_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_details` (
  `idprovider_details_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NULL,
  `provider_contact_info` TEXT NULL,
  PRIMARY KEY (`idprovider_details_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider` (
  `id_product_provider` INT NOT NULL AUTO_INCREMENT,
  `product_provider_details_id` INT NULL,
  `product_provider_type_id` INT NULL,
  `product_provider_location_id` INT NULL,
  PRIMARY KEY (`id_product_provider`),
  INDEX `fk_product_provider_3_idx` (`product_provider_details_id` ASC) VISIBLE,
  INDEX `fk_product_provider_1_idx` (`product_provider_type_id` ASC) VISIBLE,
  INDEX `fk_product_provider_4_idx` (`product_provider_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_provider_1`
    FOREIGN KEY (`product_provider_type_id`)
    REFERENCES `gluttex`.`product_provider_type` (`id_product_provider_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider_3`
    FOREIGN KEY (`product_provider_details_id`)
    REFERENCES `gluttex`.`provider_details` (`idprovider_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider_4`
    FOREIGN KEY (`product_provider_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_category` (
  `id_product_category` INT NOT NULL AUTO_INCREMENT,
  `product_category_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_brand` VARCHAR(45) NULL,
  `product_provider_id` INT NULL,
  `product_category_id` INT NULL,
  `product_barcode` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_product_1_idx` (`product_provider_id` ASC) VISIBLE,
  INDEX `fk_product_2_idx` (`product_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_1`
    FOREIGN KEY (`product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_2`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `gluttex`.`product_category` (`id_product_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`disease_severity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`disease_severity` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`disease_severity` (
  `id_disease_severity` INT NOT NULL AUTO_INCREMENT,
  `disease_severity_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_disease_severity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`patient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`patient` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `patient_person_id` INT NULL,
  `patient_disease_severity_id` INT NULL,
  PRIMARY KEY (`id_patient`),
  INDEX `fk_patient_1_idx` (`patient_person_id` ASC) VISIBLE,
  INDEX `fk_patient_2_idx` (`patient_disease_severity_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_1`
    FOREIGN KEY (`patient_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_2`
    FOREIGN KEY (`patient_disease_severity_id`)
    REFERENCES `gluttex`.`disease_severity` (`id_disease_severity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`diagnosis` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`diagnosis` (
  `id_diagnosis` INT NOT NULL AUTO_INCREMENT,
  `diagnosis_details` TEXT NULL,
  `diagnosis_date` DATE NULL,
  `patient_id` INT NULL,
  PRIMARY KEY (`id_diagnosis`),
  INDEX `fk_diagnosis_1_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `gluttex`.`patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_category` (
  `id_recipe_category` INT NOT NULL AUTO_INCREMENT,
  `recipe_category_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_recipe_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe` (
  `id_recipe` INT NOT NULL AUTO_INCREMENT,
  `recipe_owner_id` INT NULL,
  `recipe_category_id` INT NULL,
  `recipe_preparation_time` VARCHAR(45) NULL,
  `recipe_instructions` TEXT NULL,
  PRIMARY KEY (`id_recipe`),
  INDEX `fk_recipe_1_idx` (`recipe_owner_id` ASC) VISIBLE,
  INDEX `fk_recipe_2_idx` (`recipe_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_1`
    FOREIGN KEY (`recipe_owner_id`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_2`
    FOREIGN KEY (`recipe_category_id`)
    REFERENCES `gluttex`.`recipe_category` (`id_recipe_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`ingredient` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `ingredient_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_contains_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_contains_ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_contains_ingredient` (
  `idrecipe_contains_ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `containing_recipe_id` INT NULL,
  `contained_ingredient_id` INT NULL,
  `contained_quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecipe_contains_ingredient_id`),
  INDEX `fk_recipe_contains_ingredient_1_idx` (`containing_recipe_id` ASC) VISIBLE,
  INDEX `fk_recipe_contains_ingredient_2_idx` (`contained_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_contains_ingredient_1`
    FOREIGN KEY (`containing_recipe_id`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_contains_ingredient_2`
    FOREIGN KEY (`contained_ingredient_id`)
    REFERENCES `gluttex`.`ingredient` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_image` (
  `id_product_image` INT NOT NULL AUTO_INCREMENT,
  `product_image_data` BLOB NULL,
  `product_ref_id` INT NULL,
  PRIMARY KEY (`id_product_image`),
  INDEX `fk_product_image_1_idx` (`product_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_1`
    FOREIGN KEY (`product_ref_id`)
    REFERENCES `gluttex`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




INSERT INTO `gluttex`.`app_user_type` ( `app_user_type_desc`) VALUES
( 'Client'),
( 'Admin'),
( 'Cooking chef');

INSERT INTO `gluttex`.`blood_type` ( `blood_type_desc`) VALUES
('Type O+'),
('Type A+'),
('Type B+'),
('Type AB+'),
('Type O-'),
('Type A-'),
('Type B-'),
('Type AB-');

INSERT INTO `gluttex`.`product_category` ( `product_category_desc`) VALUES
('Computing'),
('Mechanical'),
('Agriculture'),
('Electronic'),
('Chemistry'),
('Medical');

INSERT INTO `gluttex`.`product_provider_type` ( `product_provider_type_desc`) VALUES
('Restaurant'),
('Factory'),
('Seller'),
('Shop');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
