-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 00:02:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gluttex` ;

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gluttex` ;
-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
USE `gluttex` ;

-- -----------------------------------------------------
-- Table `gluttex`.`product_provider_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider_type` (
  `id_product_provider_type` INT NOT NULL AUTO_INCREMENT,
  `product_provider_type_desc` VARCHAR(45) NULL DEFAULT NULL,
  `product_provider_ref` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_product_provider_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_organisation` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_organisation` (
  `idprovider_organisation` INT NOT NULL AUTO_INCREMENT,
  `provider_organisation_name` VARCHAR(45) NULL DEFAULT NULL,
  `provider_organisation_desc` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idprovider_organisation`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_details` (
  `idprovider_details_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NULL DEFAULT NULL,
  `provider_contact_info` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idprovider_details_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`address` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(45) NULL DEFAULT NULL,
  `address_city` VARCHAR(45) NULL DEFAULT NULL,
  `address_postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `address_country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`location` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `location_position` POINT NOT NULL,
  `location_name` VARCHAR(45) NULL DEFAULT NULL,
  `location_address_id` INT NULL DEFAULT NULL,
  `location_postal_code` INT NULL,
  PRIMARY KEY (`id_location`),
  INDEX `fk_location_1_idx` (`location_address_id` ASC) VISIBLE,
  SPATIAL INDEX `spatial` (`location_position`) VISIBLE,
  CONSTRAINT `fk_location_1`
    FOREIGN KEY (`location_address_id`)
    REFERENCES `gluttex`.`address` (`id_address`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`app_user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user_type` (
  `id_app_user_type` INT NOT NULL AUTO_INCREMENT,
  `app_user_type_desc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_app_user_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`plan` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`plan` (
  `id_plan` INT NOT NULL AUTO_INCREMENT,
  `plan_name` VARCHAR(45) NULL DEFAULT NULL,
  `plan_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `billing_cycle` ENUM('monthly', 'yearly') NULL DEFAULT 'monthly',
  `plan_type` ENUM('individual', 'organization') NULL DEFAULT 'individual',
  `plan_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `plan_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_plan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`person_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person_details` (
  `id_person_details` INT NOT NULL AUTO_INCREMENT,
  `person_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `person_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `person_birth_date` DATE NULL DEFAULT NULL,
  `person_gender` VARCHAR(45) NULL DEFAULT NULL,
  `person_nationality` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_person_details`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`blood_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`blood_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`blood_type` (
  `id_blood_type` INT NOT NULL AUTO_INCREMENT,
  `blood_type_desc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_blood_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `person_details_id` INT NULL DEFAULT NULL,
  `person_blood_type_id` INT NULL DEFAULT NULL,
  `person_location_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_1_idx` (`person_details_id` ASC) VISIBLE,
  INDEX `fk_person_2_idx` (`person_blood_type_id` ASC) VISIBLE,
  INDEX `fk_person_3_idx` (`person_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_1`
    FOREIGN KEY (`person_details_id`)
    REFERENCES `gluttex`.`person_details` (`id_person_details`),
  CONSTRAINT `fk_person_2`
    FOREIGN KEY (`person_blood_type_id`)
    REFERENCES `gluttex`.`blood_type` (`id_blood_type`),
  CONSTRAINT `fk_person_3`
    FOREIGN KEY (`person_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user` (
  `id_app_user` INT NOT NULL AUTO_INCREMENT,
  `app_user_name` VARCHAR(100) NULL DEFAULT NULL,
  `app_user_password` VARCHAR(256) NULL DEFAULT NULL,
  `app_user_person_id` INT NULL DEFAULT NULL,
  `app_user_type_id` INT NULL DEFAULT NULL,
  `app_user_preferences` TEXT NULL DEFAULT NULL,
  `app_user_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `app_user_last_active` TIMESTAMP NULL DEFAULT NULL,
  `app_user_last_updated` TIMESTAMP NULL DEFAULT NULL,
  `app_user_creation` TIMESTAMP NULL DEFAULT NULL,
  `app_user_subscription_ref` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_app_user`),
  INDEX `fk_app_user_3_idx` (`app_user_person_id` ASC) VISIBLE,
  INDEX `fk_app_user_1_idx` (`app_user_type_id` ASC) VISIBLE,
  INDEX `fk_app_user_2_idx` (`app_user_subscription_ref` ASC) VISIBLE,
  CONSTRAINT `fk_app_user_1`
    FOREIGN KEY (`app_user_type_id`)
    REFERENCES `gluttex`.`app_user_type` (`id_app_user_type`),
  CONSTRAINT `fk_app_user_2`
    FOREIGN KEY (`app_user_subscription_ref`)
    REFERENCES `gluttex`.`plan` (`id_plan`),
  CONSTRAINT `fk_app_user_3`
    FOREIGN KEY (`app_user_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`product_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider` (
  `id_product_provider` INT NOT NULL AUTO_INCREMENT,
  `product_provider_details_id` INT NULL DEFAULT NULL,
  `product_provider_type_id` INT NULL DEFAULT NULL,
  `product_provider_location_id` INT NULL DEFAULT NULL,
  `product_provider_org_id` INT NULL DEFAULT NULL,
  `product_provider_owner` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_product_provider`),
  INDEX `fk_product_provider_3_idx` (`product_provider_details_id` ASC) VISIBLE,
  INDEX `fk_product_provider_4_idx` (`product_provider_location_id` ASC) VISIBLE,
  INDEX `fk_product_provider_2_idx` (`product_provider_org_id` ASC) VISIBLE,
  INDEX `fk_product_provider_5_idx` (`product_provider_owner` ASC) VISIBLE,
  INDEX `fk_product_provider_1_idx` (`product_provider_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_provider_1`
    FOREIGN KEY (`product_provider_type_id`)
    REFERENCES `gluttex`.`product_provider_type` (`id_product_provider_type`),
  CONSTRAINT `fk_product_provider_2`
    FOREIGN KEY (`product_provider_org_id`)
    REFERENCES `gluttex`.`provider_organisation` (`idprovider_organisation`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_product_provider_3`
    FOREIGN KEY (`product_provider_details_id`)
    REFERENCES `gluttex`.`provider_details` (`idprovider_details_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_product_provider_4`
    FOREIGN KEY (`product_provider_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`),
  CONSTRAINT `fk_product_provider_5`
    FOREIGN KEY (`product_provider_owner`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`cart` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `cart_product_provider_id` INT NULL COMMENT 'Provider owning the cart',
  `cart_selling_user` INT NULL COMMENT 'Customer / patient / client id',
  `cart_status` VARCHAR(50) NULL DEFAULT 'open' COMMENT 'open, pending, completed, canceled',
  `cart_total_amount` DECIMAL(15,4) NULL DEFAULT '0.0000',
  `cart_notes` TEXT NULL DEFAULT NULL,
  `cart_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cart_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cart_person_ref` INT NULL,
  `cart_client_user` INT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `idx_cart_provider` (`cart_product_provider_id` ASC) VISIBLE,
  INDEX `idx_cart_user` (`cart_selling_user` ASC) VISIBLE,
  INDEX `idx_cart_status` (`cart_status` ASC) VISIBLE,
  INDEX `fk_cart_3_idx` (`cart_person_ref` ASC) VISIBLE,
  CONSTRAINT `cart_ibfk_1`
    FOREIGN KEY (`cart_product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cart_1`
    FOREIGN KEY (`cart_selling_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_2`
    FOREIGN KEY (`cart_client_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_3`
    FOREIGN KEY (`cart_person_ref`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`invoice` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_cart_id` INT NULL,
  `invoice_number` VARCHAR(100) NULL,
  `invoice_total_amount` DECIMAL(15,4) NULL,
  `invoice_status` VARCHAR(50) NULL DEFAULT 'unpaid' COMMENT 'unpaid, paid, canceled',
  `invoice_issue_date` DATE NULL,
  `invoice_due_date` DATE NULL DEFAULT NULL,
  `invoice_notes` TEXT NULL DEFAULT NULL,
  `invoice_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `invoice_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`invoice_id`),
  INDEX `idx_invoice_cart` (`invoice_cart_id` ASC) VISIBLE,
  INDEX `idx_invoice_status` (`invoice_status` ASC) VISIBLE,
  CONSTRAINT `invoice_ibfk_1`
    FOREIGN KEY (`invoice_cart_id`)
    REFERENCES `gluttex`.`cart` (`cart_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`payment` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_invoice_id` INT NULL,
  `payment_amount` DECIMAL(15,4) NULL,
  `payment_method` VARCHAR(100) NULL COMMENT 'cash, card, bank, mobile',
  `payment_status` VARCHAR(50) NULL DEFAULT 'completed',
  `payment_reference` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Bank or transaction reference',
  `payment_notes` TEXT NULL DEFAULT NULL,
  `payment_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  INDEX `idx_invoice` (`payment_invoice_id` ASC) VISIBLE,
  INDEX `idx_status` (`payment_status` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`payment_invoice_id`)
    REFERENCES `gluttex`.`invoice` (`invoice_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`additional_fee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`additional_fee` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`additional_fee` (
  `additional_fee_id` INT NOT NULL AUTO_INCREMENT,
  `additional_fee_payment_id` INT NULL,
  `additional_fee_name` VARCHAR(255) NULL,
  `additional_fee_amount` DECIMAL(15,4) NULL,
  `additional_fee_description` TEXT NULL DEFAULT NULL,
  `additional_fee_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `additional_fee_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `additional_fee_document_url` VARCHAR(255) NULL,
  `additional_fee_user_id` INT NULL,
  `additional_fee_on_provider_id` INT NULL,
  PRIMARY KEY (`additional_fee_id`),
  INDEX `idx_payment` (`additional_fee_payment_id` ASC) VISIBLE,
  INDEX `fk_additional_fee_1_idx` (`additional_fee_user_id` ASC) VISIBLE,
  INDEX `fk_additional_fee_2_idx` (`additional_fee_on_provider_id` ASC) VISIBLE,
  CONSTRAINT `additional_fee_ibfk_1`
    FOREIGN KEY (`additional_fee_payment_id`)
    REFERENCES `gluttex`.`payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_additional_fee_1`
    FOREIGN KEY (`additional_fee_user_id`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_additional_fee_2`
    FOREIGN KEY (`additional_fee_on_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`comment` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `comment_owner` INT NULL DEFAULT NULL,
  `comment_content` TEXT NULL DEFAULT NULL,
  `replying_to` INT NULL DEFAULT NULL,
  `comment_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `comment_visibility` TINYINT NULL DEFAULT NULL,
  `comment_edition` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_1_idx` (`replying_to` ASC) VISIBLE,
  INDEX `fk_comment_2_idx` (`comment_owner` ASC) VISIBLE,
  CONSTRAINT `fk_comment_1`
    FOREIGN KEY (`replying_to`)
    REFERENCES `gluttex`.`comment` (`idcomment`),
  CONSTRAINT `fk_comment_2`
    FOREIGN KEY (`comment_owner`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`reaction` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`reaction` (
  `id_reaction` INT NOT NULL AUTO_INCREMENT,
  `reaction_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reaction`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`comment_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`comment_reaction` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`comment_reaction` (
  `id_comment_reaction` INT NOT NULL AUTO_INCREMENT,
  `comment_reacting_user` INT NULL DEFAULT NULL,
  `comment_reaction_ref` INT NULL DEFAULT NULL,
  `reacted_on_comment` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_comment_reaction`),
  INDEX `fk_product_reaction_1_idx` (`comment_reacting_user` ASC) VISIBLE,
  INDEX `fk_product_reaction_2_idx` (`comment_reaction_ref` ASC) VISIBLE,
  INDEX `fk_product_reaction_30_idx` (`reacted_on_comment` ASC) VISIBLE,
  CONSTRAINT `fk_product_reaction_11`
    FOREIGN KEY (`comment_reacting_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`),
  CONSTRAINT `fk_product_reaction_21`
    FOREIGN KEY (`comment_reaction_ref`)
    REFERENCES `gluttex`.`reaction` (`id_reaction`),
  CONSTRAINT `fk_product_reaction_30`
    FOREIGN KEY (`reacted_on_comment`)
    REFERENCES `gluttex`.`comment` (`idcomment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`receipt` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`receipt` (
  `receipt_id` INT NOT NULL AUTO_INCREMENT,
  `receipt_payment_id` INT NULL,
  `receipt_number` VARCHAR(100) NULL,
  `receipt_amount` DECIMAL(15,4) NOT NULL,
  `receipt_notes` TEXT NULL DEFAULT NULL,
  `receipt_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `receipt_cart_ref` INT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `idx_payment` (`receipt_payment_id` ASC) VISIBLE,
  INDEX `fk_receipt_1_idx` (`receipt_cart_ref` ASC) VISIBLE,
  CONSTRAINT `receipt_ibfk_1`
    FOREIGN KEY (`receipt_payment_id`)
    REFERENCES `gluttex`.`payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_receipt_1`
    FOREIGN KEY (`receipt_cart_ref`)
    REFERENCES `gluttex`.`cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`deposit` ;
CREATE TABLE IF NOT EXISTS `gluttex`.`deposit` (
  `deposit_id` INT NOT NULL AUTO_INCREMENT,
  `deposit_cart_id` INT NULL DEFAULT NULL,
  `deposit_invoice_id` INT NULL DEFAULT NULL,
  `deposit_amount` DECIMAL(15,4) NOT NULL,
  `deposit_method` VARCHAR(100) NOT NULL,
  `deposit_reference` VARCHAR(255) NULL DEFAULT NULL,
  `deposit_notes` TEXT NULL DEFAULT NULL,
  `deposit_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deposit_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deposit_receipt_id` INT NULL,
  PRIMARY KEY (`deposit_id`),
  INDEX `idx_cart` (`deposit_cart_id` ASC) VISIBLE,
  INDEX `idx_invoice` (`deposit_invoice_id` ASC) VISIBLE,
  INDEX `fk_deposit_1_idx` (`deposit_receipt_id` ASC) VISIBLE,
  CONSTRAINT `deposit_ibfk_1`
    FOREIGN KEY (`deposit_cart_id`)
    REFERENCES `gluttex`.`cart` (`cart_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `deposit_ibfk_2`
    FOREIGN KEY (`deposit_invoice_id`)
    REFERENCES `gluttex`.`invoice` (`invoice_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deposit_1`
    FOREIGN KEY (`deposit_receipt_id`)
    REFERENCES `gluttex`.`receipt` (`receipt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `gluttex`.`disease_severity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`disease_severity` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`disease_severity` (
  `id_disease_severity` INT NOT NULL AUTO_INCREMENT,
  `disease_severity_desc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_disease_severity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`ingredient` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `ingredient_name` VARCHAR(45) NULL DEFAULT NULL,
  `ingredient_icon_url` VARCHAR(255) NULL DEFAULT NULL,
  `ingredient_quantifier` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_category` (
  `id_product_category` INT NOT NULL AUTO_INCREMENT,
  `product_category_desc` VARCHAR(45) NULL DEFAULT NULL,
  `product_category_icon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_product_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`iproduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`iproduct` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`iproduct` (
  `id_iproduct` INT NOT NULL AUTO_INCREMENT,
  `iproduct_barcode` VARCHAR(45) NULL DEFAULT NULL,
  `iproduct_brand` VARCHAR(255) NULL DEFAULT NULL,
  `iproduct_estimated_price` DECIMAL(8,2) NULL DEFAULT '0.00',
  `iproduct_price_currency` VARCHAR(45) NULL DEFAULT 'DZD',
  `iproduct_gluten_status` ENUM('gluten_free', 'contains_gluten', 'may_contain_gluten', 'unknown') NULL DEFAULT 'unknown',
  `iproduct_info_source` VARCHAR(255) NULL DEFAULT NULL,
  `iproduct_last_price_update` DATETIME NULL DEFAULT NULL,
  `iproduct_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `iproduct_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `iproduct_model_name` VARCHAR(255) NULL DEFAULT NULL,
  `iproduct_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `iproduct_name` VARCHAR(255) NULL DEFAULT NULL,
  `iproduct_info_confidence` DECIMAL(5,4) NULL DEFAULT NULL,
  `iproduct_category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_iproduct`),
  INDEX `fk_iproduct_1_idx` (`iproduct_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_iproduct_1`
    FOREIGN KEY (`iproduct_category_id`)
    REFERENCES `gluttex`.`product_category` (`id_product_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`location_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`location_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`location_image` (
  `id_location_image` INT NOT NULL AUTO_INCREMENT,
  `location_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `image_location_ref` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_location_image`),
  INDEX `fk_location_image_1_idx` (`image_location_ref` ASC) VISIBLE,
  CONSTRAINT `fk_location_image_1`
    FOREIGN KEY (`image_location_ref`)
    REFERENCES `gluttex`.`location` (`id_location`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`management_rule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`management_rule` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`management_rule` (
  `id_management_rule` INT NOT NULL AUTO_INCREMENT,
  `rule_ref_org` INT NULL DEFAULT NULL,
  `rule_ref_provider` INT NULL DEFAULT NULL,
  `rule_ref_user` INT NULL DEFAULT NULL,
  `management_rule_code` INT NULL DEFAULT NULL,
  `management_rule_status` ENUM('PENDING', 'REJECTED', 'SUSPENDED', 'OBSOLETE', 'ACTIVE') NULL DEFAULT 'PENDING',
  `management_rule_expiry` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_management_rule`),
  INDEX `fk_management_rule_1_idx` (`rule_ref_org` ASC) VISIBLE,
  INDEX `fk_management_rule_2_idx` (`rule_ref_provider` ASC) VISIBLE,
  INDEX `fk_management_rule_3_idx` (`rule_ref_user` ASC) VISIBLE,
  CONSTRAINT `fk_management_rule_1`
    FOREIGN KEY (`rule_ref_org`)
    REFERENCES `gluttex`.`provider_organisation` (`idprovider_organisation`),
  CONSTRAINT `fk_management_rule_2`
    FOREIGN KEY (`rule_ref_provider`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`),
  CONSTRAINT `fk_management_rule_3`
    FOREIGN KEY (`rule_ref_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`notification` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`notification` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `notification_code` VARCHAR(255) NULL DEFAULT NULL,
  `notification_params` TEXT NULL DEFAULT NULL,
  `notification_user_ref` INT NULL DEFAULT NULL,
  `notification_created_at` DATETIME NULL DEFAULT NULL,
  `notification_read_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_notification`),
  INDEX `fk_notification_1_idx` (`notification_user_ref` ASC) VISIBLE,
  CONSTRAINT `fk_notification_1`
    FOREIGN KEY (`notification_user_ref`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `product_brand` VARCHAR(45) NULL DEFAULT NULL,
  `product_provider_id` INT NULL DEFAULT NULL,
  `product_category_id` INT NULL DEFAULT NULL,
  `product_barcode` VARCHAR(45) NULL DEFAULT NULL,
  `last_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `product_description` VARCHAR(300) NULL DEFAULT NULL,
  `product_price` DOUBLE NULL DEFAULT NULL,
  `product_quantity` INT NULL DEFAULT NULL,
  `product_quantifier` VARCHAR(45) NULL DEFAULT NULL,
  `product_owner` INT NULL DEFAULT NULL,
  `product_origin_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_product_1_idx` (`product_provider_id` ASC) VISIBLE,
  INDEX `fk_product_2_idx` (`product_category_id` ASC) VISIBLE,
  INDEX `fk_product_3_idx` (`product_owner` ASC) VISIBLE,
  INDEX `fk_product_4_idx` (`product_origin_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_1`
    FOREIGN KEY (`product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`),
  CONSTRAINT `fk_product_2`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `gluttex`.`product_category` (`id_product_category`),
  CONSTRAINT `fk_product_3`
    FOREIGN KEY (`product_owner`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_product_4`
    FOREIGN KEY (`product_origin_id`)
    REFERENCES `gluttex`.`iproduct` (`id_iproduct`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`delivery` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `recipient_person` INT NULL,
  `recipient_provider` INT NULL,
  `delivery_package_count` VARCHAR(45) NULL,
  `delivery_total_weight` DECIMAL NULL,
  `delivery_cargo_dimensions` VARCHAR(255) NULL,
  `delivery_goods_description` TEXT NULL,
  `hs_code` VARCHAR(255) NULL,
  `delivery_merchant_name` VARCHAR(255) NULL,
  `delivery_shipping_method` VARCHAR(255) NULL,
  `delivery_special_instructions` VARCHAR(45) NULL,
  `delivery_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `delivery_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delivery_status` VARCHAR(255) NULL DEFAULT 'PENDING',
  PRIMARY KEY (`id_delivery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`placed_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`placed_order` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`placed_order` (
  `id_placed_order` INT NOT NULL AUTO_INCREMENT,
  `order_discount` DOUBLE NULL DEFAULT NULL,
  `total_price` DOUBLE NULL DEFAULT NULL,
  `ordering_user_id` INT NULL DEFAULT NULL,
  `placed_order_location_ref` INT NULL DEFAULT NULL,
  `placed_order_state_ref` INT NULL DEFAULT NULL,
  `placed_order_last_mod` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `placed_order_invoice_ref` INT NULL,
  `placed_order_receipt_ref` INT NULL,
  `placed_order_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `placed_order_delivery` INT NULL,
  PRIMARY KEY (`id_placed_order`),
  INDEX `fk_placed_order_1_idx` (`ordering_user_id` ASC) VISIBLE,
  INDEX `fk_placed_order_2_idx` (`placed_order_location_ref` ASC) VISIBLE,
  INDEX `fk_placed_order_3_idx` (`placed_order_receipt_ref` ASC) VISIBLE,
  INDEX `fk_placed_order_4_idx` (`placed_order_invoice_ref` ASC) VISIBLE,
  INDEX `fk_placed_order_5_idx` (`placed_order_delivery` ASC) VISIBLE,
  CONSTRAINT `fk_placed_order_1`
    FOREIGN KEY (`ordering_user_id`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_placed_order_2`
    FOREIGN KEY (`placed_order_location_ref`)
    REFERENCES `gluttex`.`location` (`id_location`),
  CONSTRAINT `fk_placed_order_3`
    FOREIGN KEY (`placed_order_receipt_ref`)
    REFERENCES `gluttex`.`receipt` (`receipt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_placed_order_4`
    FOREIGN KEY (`placed_order_invoice_ref`)
    REFERENCES `gluttex`.`invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_placed_order_5`
    FOREIGN KEY (`placed_order_delivery`)
    REFERENCES `gluttex`.`delivery` (`id_delivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`ordered_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`ordered_item` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`ordered_item` (
  `id_ordered_item` INT NOT NULL AUTO_INCREMENT,
  `ordered_product_id` INT NULL DEFAULT NULL,
  `ordered_quantity` INT NULL DEFAULT NULL,
  `applied_vat` DOUBLE NULL DEFAULT NULL,
  `order_ref` INT NULL DEFAULT NULL,
  `unit_price` DOUBLE NULL DEFAULT NULL,
  `product_discount` DOUBLE NULL DEFAULT NULL,
  `ordered_item_cart_ref` INT NULL,
  PRIMARY KEY (`id_ordered_item`),
  INDEX `fk_ordered_item_1_idx` (`ordered_product_id` ASC) VISIBLE,
  INDEX `fk_ordered_item_3_idx` (`order_ref` ASC) VISIBLE,
  INDEX `fk_ordered_item_2_idx` (`ordered_item_cart_ref` ASC) VISIBLE,
  CONSTRAINT `fk_ordered_item_1`
    FOREIGN KEY (`ordered_product_id`)
    REFERENCES `gluttex`.`product` (`id_product`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ordered_item_3`
    FOREIGN KEY (`order_ref`)
    REFERENCES `gluttex`.`placed_order` (`id_placed_order`),
  CONSTRAINT `fk_ordered_item_2`
    FOREIGN KEY (`ordered_item_cart_ref`)
    REFERENCES `gluttex`.`cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provided_service_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provided_service_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provided_service_category` (
  `provided_service_category_id` INT NOT NULL AUTO_INCREMENT,
  `provided_service_category_name` VARCHAR(255) NULL,
  `provided_service_category_icon_url` VARCHAR(500) NULL,
  `provided_service_category_avg_duration` DECIMAL(10,2) NULL COMMENT 'Average duration in minutes',
  `provided_service_category_description` TEXT NULL DEFAULT NULL,
  `provided_service_category_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `provided_service_category_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `provided_service_category_deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`provided_service_category_id`),
  INDEX `idx_provided_service_category_name` (`provided_service_category_name` ASC) VISIBLE,
  INDEX `idx_provided_service_category_created_at` (`provided_service_category_created_at` ASC) VISIBLE,
  INDEX `idx_provided_service_category_active` (`provided_service_category_deleted_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provided_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provided_service` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provided_service` (
  `provided_service_id` INT NOT NULL AUTO_INCREMENT,
  `provided_service_name` VARCHAR(255) NULL,
  `provided_service_description` TEXT NULL DEFAULT NULL,
  `provided_service_category_id` INT NULL,
  `provided_service_product_provider_id` INT NULL COMMENT 'References i_product_provider.id_product_provider',
  `provided_service_base_price` DECIMAL(15,4) NULL,
  `provided_service_final_price` DECIMAL(15,4) NULL,
  `provided_service_actual_duration` DECIMAL(10,2) NULL,
  `provided_service_is_active` TINYINT(1) NULL DEFAULT '1',
  `provided_service_pricing_config` JSON NULL,
  `provided_service_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `provided_service_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `provided_service_deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`provided_service_id`),
  INDEX `idx_provided_service_category` (`provided_service_category_id` ASC) VISIBLE,
  INDEX `idx_provided_service_provider` (`provided_service_product_provider_id` ASC) VISIBLE,
  INDEX `idx_provided_service_name` (`provided_service_name` ASC) VISIBLE,
  INDEX `idx_provided_service_active` (`provided_service_is_active` ASC, `provided_service_deleted_at` ASC) VISIBLE,
  INDEX `idx_provided_service_price_range` (`provided_service_base_price` ASC, `provided_service_final_price` ASC) VISIBLE,
  INDEX `idx_provided_service_created_at` (`provided_service_created_at` ASC) VISIBLE,
  CONSTRAINT `provided_service_ibfk_1`
    FOREIGN KEY (`provided_service_category_id`)
    REFERENCES `gluttex`.`provided_service_category` (`provided_service_category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `provided_service_ibfk_2`
    FOREIGN KEY (`provided_service_product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`ordered_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`ordered_service` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`ordered_service` (
  `ordered_service_id` INT NOT NULL AUTO_INCREMENT,
  `ordered_service_cart_id` INT NULL,
  `ordered_service_service_id` INT NULL COMMENT 'References provided_service',
  `ordered_service_quantity` INT NULL DEFAULT '1',
  `ordered_service_unit_price` DECIMAL(15,4) NULL,
  `ordered_service_total_price` DECIMAL(15,4) NULL,
  `ordered_service_notes` TEXT NULL DEFAULT NULL,
  `ordered_service_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ordered_service_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ordered_service_id`),
  INDEX `idx_cart` (`ordered_service_cart_id` ASC) VISIBLE,
  INDEX `idx_service` (`ordered_service_service_id` ASC) VISIBLE,
  CONSTRAINT `ordered_service_ibfk_1`
    FOREIGN KEY (`ordered_service_cart_id`)
    REFERENCES `gluttex`.`cart` (`cart_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ordered_service_ibfk_2`
    FOREIGN KEY (`ordered_service_service_id`)
    REFERENCES `gluttex`.`provided_service` (`provided_service_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`organisation_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`organisation_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`organisation_image` (
  `id_org_image` INT NOT NULL AUTO_INCREMENT,
  `org_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `org_ref_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_org_image`),
  INDEX `fk_organisation_image_1_idx` (`org_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_organisation_image_1`
    FOREIGN KEY (`org_ref_id`)
    REFERENCES `gluttex`.`provider_organisation` (`idprovider_organisation`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`patient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`patient` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `patient_person_id` INT NULL DEFAULT NULL,
  `patient_disease_severity_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_patient`),
  INDEX `fk_patient_1_idx` (`patient_person_id` ASC) VISIBLE,
  INDEX `fk_patient_2_idx` (`patient_disease_severity_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_1`
    FOREIGN KEY (`patient_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`),
  CONSTRAINT `fk_patient_2`
    FOREIGN KEY (`patient_disease_severity_id`)
    REFERENCES `gluttex`.`disease_severity` (`id_disease_severity`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`symptom` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`symptom` (
  `id_symptom` INT NOT NULL AUTO_INCREMENT,
  `symptom_name` VARCHAR(45) NULL DEFAULT NULL,
  `symptom_desc` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_symptom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`symptoms_occurence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`symptoms_occurence` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`symptoms_occurence` (
  `id_symptoms_occurence` INT NOT NULL AUTO_INCREMENT,
  `symptoms_occurence_submission_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `symptoms_occurence_reason` VARCHAR(300) NULL DEFAULT NULL,
  `reason_date` TIMESTAMP NULL DEFAULT NULL,
  `symptoms_occurence_ref_patient` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_symptoms_occurence`),
  INDEX `fk_symptoms_causality_1_idx` (`symptoms_occurence_ref_patient` ASC) VISIBLE,
  CONSTRAINT `fk_symptoms_causality_1`
    FOREIGN KEY (`symptoms_occurence_ref_patient`)
    REFERENCES `gluttex`.`patient` (`id_patient`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`presented_symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`presented_symptom` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`presented_symptom` (
  `id_presented_symptom` INT NOT NULL AUTO_INCREMENT,
  `presented_symptom_ref_symptoms_occurence` INT NULL DEFAULT NULL,
  `presented_symptom_ref_symptom` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_presented_symptom`),
  INDEX `fk_presented_symptom_1_idx` (`presented_symptom_ref_symptom` ASC) VISIBLE,
  INDEX `fk_presented_symptom_2_idx` (`presented_symptom_ref_symptoms_occurence` ASC) VISIBLE,
  CONSTRAINT `fk_presented_symptom_1`
    FOREIGN KEY (`presented_symptom_ref_symptom`)
    REFERENCES `gluttex`.`symptom` (`id_symptom`),
  CONSTRAINT `fk_presented_symptom_2`
    FOREIGN KEY (`presented_symptom_ref_symptoms_occurence`)
    REFERENCES `gluttex`.`symptoms_occurence` (`id_symptoms_occurence`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_image` (
  `id_product_image` INT NOT NULL AUTO_INCREMENT,
  `product_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `product_ref_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_product_image`),
  INDEX `fk_product_image_1_idx` (`product_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_1`
    FOREIGN KEY (`product_ref_id`)
    REFERENCES `gluttex`.`product` (`id_product`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`product_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_reaction` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_reaction` (
  `id_product_reaction` INT NOT NULL AUTO_INCREMENT,
  `product_reacting_user` INT NULL DEFAULT NULL,
  `product_reaction_ref` INT NULL DEFAULT NULL,
  `reacted_on_product` INT NULL DEFAULT NULL,
  `product_reaction_value` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`id_product_reaction`),
  INDEX `fk_product_reaction_1_idx` (`product_reacting_user` ASC) VISIBLE,
  INDEX `fk_product_reaction_2_idx` (`product_reaction_ref` ASC) VISIBLE,
  INDEX `fk_product_reaction_3_idx` (`reacted_on_product` ASC) VISIBLE,
  CONSTRAINT `fk_product_reaction_1`
    FOREIGN KEY (`product_reacting_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`),
  CONSTRAINT `fk_product_reaction_2`
    FOREIGN KEY (`product_reaction_ref`)
    REFERENCES `gluttex`.`reaction` (`id_reaction`),
  CONSTRAINT `fk_product_reaction_3`
    FOREIGN KEY (`reacted_on_product`)
    REFERENCES `gluttex`.`product` (`id_product`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_image` (
  `id_provider_image` INT NOT NULL AUTO_INCREMENT,
  `provider_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `provider_ref_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_provider_image`),
  INDEX `fk_provider_image_1_idx` (`provider_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_provider_image_1`
    FOREIGN KEY (`provider_ref_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_reaction` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_reaction` (
  `id_product_reaction` INT NOT NULL AUTO_INCREMENT,
  `product_reacting_user` INT NULL DEFAULT NULL,
  `product_reaction_ref` INT NULL DEFAULT NULL,
  `reacted_on_provider` INT NULL DEFAULT NULL,
  `provider_reaction_value` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`id_product_reaction`),
  INDEX `fk_product_reaction_1_idx` (`product_reacting_user` ASC) VISIBLE,
  INDEX `fk_product_reaction_2_idx` (`product_reaction_ref` ASC) VISIBLE,
  INDEX `fk_product_reaction_31_idx` (`reacted_on_provider` ASC) VISIBLE,
  CONSTRAINT `fk_product_reaction_12`
    FOREIGN KEY (`product_reacting_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`),
  CONSTRAINT `fk_product_reaction_22`
    FOREIGN KEY (`product_reaction_ref`)
    REFERENCES `gluttex`.`reaction` (`id_reaction`),
  CONSTRAINT `fk_product_reaction_31`
    FOREIGN KEY (`reacted_on_provider`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_category` (
  `id_recipe_category` INT NOT NULL AUTO_INCREMENT,
  `recipe_category_desc` VARCHAR(45) NULL DEFAULT NULL,
  `recipe_category_icon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recipe_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe` (
  `id_recipe` INT NOT NULL AUTO_INCREMENT,
  `recipe_owner_id` INT NULL DEFAULT NULL,
  `recipe_category_id` INT NULL DEFAULT NULL,
  `recipe_preparation_time` VARCHAR(45) NULL DEFAULT NULL,
  `recipe_instructions` TEXT NULL DEFAULT NULL,
  `recipe_name` VARCHAR(45) NULL DEFAULT NULL,
  `recipe_description` VARCHAR(300) NULL DEFAULT NULL,
  `recipe_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `recipe_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_recipe`),
  INDEX `fk_recipe_1_idx` (`recipe_owner_id` ASC) VISIBLE,
  INDEX `fk_recipe_2_idx` (`recipe_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_1`
    FOREIGN KEY (`recipe_owner_id`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`),
  CONSTRAINT `fk_recipe_2`
    FOREIGN KEY (`recipe_category_id`)
    REFERENCES `gluttex`.`recipe_category` (`id_recipe_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_contains_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_contains_ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_contains_ingredient` (
  `idrecipe_contains_ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `containing_recipe_id` INT NULL DEFAULT NULL,
  `contained_ingredient_id` INT NULL DEFAULT NULL,
  `contained_quantity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idrecipe_contains_ingredient_id`),
  INDEX `fk_recipe_contains_ingredient_1_idx` (`containing_recipe_id` ASC) VISIBLE,
  INDEX `fk_recipe_contains_ingredient_2_idx` (`contained_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_contains_ingredient_1`
    FOREIGN KEY (`containing_recipe_id`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`),
  CONSTRAINT `fk_recipe_contains_ingredient_2`
    FOREIGN KEY (`contained_ingredient_id`)
    REFERENCES `gluttex`.`ingredient` (`id_ingredient`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_image` (
  `id_recipe_image` INT NOT NULL AUTO_INCREMENT,
  `recipe_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `recipe_ref_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_recipe_image`),
  INDEX `fk_recipe_image_1_idx` (`recipe_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_image_1`
    FOREIGN KEY (`recipe_ref_id`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_reaction` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_reaction` (
  `id_recipe_reaction` INT NOT NULL AUTO_INCREMENT,
  `recipe_reacting_user` INT NULL DEFAULT NULL,
  `recipe_reaction_ref` INT NULL DEFAULT NULL,
  `reacted_on_recipe` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_recipe_reaction`),
  INDEX `fk_product_reaction_1_idx` (`recipe_reacting_user` ASC) VISIBLE,
  INDEX `fk_product_reaction_2_idx` (`recipe_reaction_ref` ASC) VISIBLE,
  INDEX `fk_recipe_reaction_1_idx` (`reacted_on_recipe` ASC) VISIBLE,
  CONSTRAINT `fk_product_reaction_10`
    FOREIGN KEY (`recipe_reacting_user`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`),
  CONSTRAINT `fk_product_reaction_20`
    FOREIGN KEY (`recipe_reaction_ref`)
    REFERENCES `gluttex`.`reaction` (`id_reaction`),
  CONSTRAINT `fk_recipe_reaction_1`
    FOREIGN KEY (`reacted_on_recipe`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`report` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`report` (
  `id_report` INT NOT NULL AUTO_INCREMENT,
  `report_text` TEXT NULL DEFAULT NULL,
  `report_owner` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_report`),
  INDEX `fk_report_1_idx` (`report_owner` ASC) VISIBLE,
  CONSTRAINT `fk_report_1`
    FOREIGN KEY (`report_owner`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`serology_indicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`serology_indicator` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`serology_indicator` (
  `id_serology_indicator` INT NOT NULL AUTO_INCREMENT,
  `serology_indicator_name` VARCHAR(45) NULL DEFAULT NULL,
  `serology_indicator_desc` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_serology_indicator`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`serology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`serology` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`serology` (
  `id_serology` INT NOT NULL AUTO_INCREMENT,
  `indicator_id` INT NULL DEFAULT NULL,
  `serology_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `patient_id` INT NULL DEFAULT NULL,
  `indicator_value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_serology`),
  INDEX `fk_diagnosis_1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_serology_1_idx` (`indicator_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `gluttex`.`patient` (`id_patient`),
  CONSTRAINT `fk_serology_1`
    FOREIGN KEY (`indicator_id`)
    REFERENCES `gluttex`.`serology_indicator` (`id_serology_indicator`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`service_package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`service_package` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`service_package` (
  `service_package_id` INT NOT NULL AUTO_INCREMENT,
  `service_package_name` VARCHAR(255) NULL,
  `service_package_description` TEXT NULL DEFAULT NULL,
  `service_package_product_provider_id` INT NULL,
  `service_package_price` DECIMAL(15,4) NULL,
  `service_package_discount_percentage` DECIMAL(5,2) NULL DEFAULT NULL,
  `service_package_is_active` TINYINT(1) NULL DEFAULT '1',
  `service_package_valid_from` DATE NULL DEFAULT NULL,
  `service_package_valid_to` DATE NULL DEFAULT NULL,
  `service_package_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `service_package_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`service_package_id`),
  INDEX `idx_service_package_provider` (`service_package_product_provider_id` ASC) VISIBLE,
  INDEX `idx_service_package_active` (`service_package_is_active` ASC) VISIBLE,
  INDEX `idx_service_package_validity` (`service_package_valid_from` ASC, `service_package_valid_to` ASC) VISIBLE,
  CONSTRAINT `service_package_ibfk_1`
    FOREIGN KEY (`service_package_product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`service_package_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`service_package_item` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`service_package_item` (
  `service_package_item_id` INT NOT NULL AUTO_INCREMENT,
  `service_package_item_package_id` INT NULL,
  `service_package_item_service_id` INT NULL,
  `service_package_item_sequence_order` INT NULL DEFAULT '1',
  `service_package_item_quantity` INT NULL DEFAULT '1',
  `service_package_item_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`service_package_item_id`),
  UNIQUE INDEX `uk_package_service` (`service_package_item_package_id` ASC, `service_package_item_service_id` ASC) VISIBLE,
  INDEX `idx_service_package_item_service` (`service_package_item_service_id` ASC) VISIBLE,
  CONSTRAINT `service_package_item_ibfk_1`
    FOREIGN KEY (`service_package_item_package_id`)
    REFERENCES `gluttex`.`service_package` (`service_package_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `service_package_item_ibfk_2`
    FOREIGN KEY (`service_package_item_service_id`)
    REFERENCES `gluttex`.`provided_service` (`provided_service_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`service_resource_requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`service_resource_requirement` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`service_resource_requirement` (
  `service_resource_requirement_id` INT NOT NULL AUTO_INCREMENT,
  `service_resource_requirement_service_id` INT NULL,
  `service_resource_requirement_name` VARCHAR(255) NULL,
  `service_resource_requirement_type` VARCHAR(100) NULL DEFAULT NULL,
  `service_resource_requirement_quantity` INT NULL DEFAULT '1',
  `service_resource_requirement_cost_per_unit` DECIMAL(15,4) NULL DEFAULT NULL,
  `service_resource_requirement_is_consumable` TINYINT(1) NULL DEFAULT '0',
  `service_resource_requirement_notes` TEXT NULL DEFAULT NULL,
  `service_resource_requirement_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `service_resource_requirement_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `service_resource_requirement_product_ref` INT NULL,
  PRIMARY KEY (`service_resource_requirement_id`),
  INDEX `idx_resource_requirement_service` (`service_resource_requirement_service_id` ASC) VISIBLE,
  INDEX `idx_resource_requirement_name` (`service_resource_requirement_name` ASC) VISIBLE,
  INDEX `idx_resource_requirement_type` (`service_resource_requirement_type` ASC) VISIBLE,
  INDEX `fk_service_resource_requirement_1_idx` (`service_resource_requirement_product_ref` ASC) VISIBLE,
  CONSTRAINT `service_resource_requirement_ibfk_1`
    FOREIGN KEY (`service_resource_requirement_service_id`)
    REFERENCES `gluttex`.`provided_service` (`provided_service_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_service_resource_requirement_1`
    FOREIGN KEY (`service_resource_requirement_product_ref`)
    REFERENCES `gluttex`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`service_staff_requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`service_staff_requirement` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`service_staff_requirement` (
  `service_staff_requirement_id` INT NOT NULL AUTO_INCREMENT,
  `service_staff_requirement_service_id` INT NULL,
  `service_staff_requirement_role` VARCHAR(100) NULL,
  `service_staff_requirement_min_count` INT NULL DEFAULT '1',
  `service_staff_requirement_max_count` INT NULL DEFAULT NULL,
  `service_staff_requirement_hourly_rate` DECIMAL(15,4) NULL DEFAULT NULL,
  `service_staff_requirement_allocated_hours` DECIMAL(5,2) NULL DEFAULT NULL,
  `service_staff_requirement_notes` TEXT NULL DEFAULT NULL,
  `service_staff_requirement_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `service_staff_requirement_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`service_staff_requirement_id`),
  INDEX `idx_service_staff_requirement_service` (`service_staff_requirement_service_id` ASC) VISIBLE,
  INDEX `idx_service_staff_requirement_role` (`service_staff_requirement_role` ASC) VISIBLE,
  CONSTRAINT `service_staff_requirement_ibfk_1`
    FOREIGN KEY (`service_staff_requirement_service_id`)
    REFERENCES `gluttex`.`provided_service` (`provided_service_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gluttex`.`service_contribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`service_contribution` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`service_contribution` (
  `id_service_contribution` INT NOT NULL AUTO_INCREMENT,
  `service_contribution_duration` VARCHAR(45) NULL,
  `service_contribution_price` FLOAT NULL,
  `service_contribution_currency` VARCHAR(45) NULL,
  `service_contribution_org_ref` INT NULL,
  `service_contribution_user_ref` INT NULL,
  `service_contribution_person_ref` INT NULL,
  `service_ref` INT NULL,
  `service_contribution_start` TIMESTAMP NULL,
  `service_contribution_provider_ref` INT NULL,
  PRIMARY KEY (`id_service_contribution`),
  INDEX `fk_service_contribution_2_idx` (`service_contribution_org_ref` ASC) VISIBLE,
  INDEX `fk_service_contribution_3_idx` (`service_contribution_user_ref` ASC) VISIBLE,
  INDEX `fk_service_contribution_4_idx` (`service_contribution_person_ref` ASC) VISIBLE,
  INDEX `fk_service_contribution_5_idx` (`service_ref` ASC) VISIBLE,
  INDEX `fk_service_contribution_6_idx` (`service_contribution_provider_ref` ASC) VISIBLE,
  CONSTRAINT `fk_service_contribution_2`
    FOREIGN KEY (`service_contribution_org_ref`)
    REFERENCES `gluttex`.`provider_organisation` (`idprovider_organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_contribution_3`
    FOREIGN KEY (`service_contribution_user_ref`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_contribution_4`
    FOREIGN KEY (`service_contribution_person_ref`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_contribution_5`
    FOREIGN KEY (`service_ref`)
    REFERENCES `gluttex`.`provided_service` (`provided_service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_contribution_6`
    FOREIGN KEY (`service_contribution_provider_ref`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gluttex` ;

-- -----------------------------------------------------
-- Placeholder table for view `gluttex`.`business_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gluttex`.`business_operation` (`supplier_id` INT, `order_id` INT, `cart_id` INT, `client` INT, `seller_id` INT, `total_amount` INT, `invoice_status` INT, `total_paid` INT, `total_deposited` INT, `balance_due` INT, `payment_status` INT, `source_table` INT);

-- -----------------------------------------------------
-- View `gluttex`.`business_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`business_operation`;
DROP VIEW IF EXISTS `gluttex`.`business_operation` ;
USE `gluttex`;
-- -----------------------------------------------------
-- View: business_operation
-- -----------------------------------------------------
-- 
-- BUSINESS OPERATIONS CONSOLIDATION VIEW
-- ======================================
-- 
-- PURPOSE:
-- This view consolidates all business transactions from two sources:
-- 1. Cart-based operations (standard shopping cart flow)
-- 2. Order-based items (legacy/alternate order system)
-- 
-- SOURCES:
-- • cart table (via cart_id)
-- • ordered_item table (where cart_ref is null but order_ref exists)
-- 
-- KEY FEATURES:
-- • Unified view of all financial transactions
-- • Payment status tracking (paid/partial/unpaid)
-- • Supplier performance analysis
-- • Balance due calculations
-- • Source type identification (cart_based / order_based)
-- 
-- COMMON USE CASES:
-- • Financial reporting and reconciliation
-- • Supplier performance monitoring
-- • Accounts receivable tracking
-- • Business analytics and dashboards
-- 
-- NOTE: This is a read-only view. Updates must be made to underlying tables.
-- -----------------------------------------------------






CREATE OR REPLACE VIEW business_operation AS
-- PART 1: Complete Cart-based operations with ALL financial scenarios
SELECT 
    -- Supplier information from cart's product provider
    pp.id_product_provider AS supplier_id,
    
    -- Order information (if order exists)
    po.id_placed_order AS order_id,
    
    -- Cart information
    c.cart_id,
    
    -- Client information
    COALESCE(c.cart_client_user, c.cart_selling_user) AS client_id,
    
    -- Seller information
    COALESCE(c.cart_selling_user, c.cart_client_user) AS seller_id,
    
    -- Financial information (use highest available amount)
    COALESCE(
        i.invoice_total_amount, 
        r.receipt_amount, 
        c.cart_total_amount, 
        0
    ) AS total_amount,
    
    -- Invoice information
    i.invoice_id,
    COALESCE(i.invoice_status, 
        CASE WHEN r.receipt_id IS NOT NULL THEN 'receipt_only'
             WHEN EXISTS (SELECT 1 FROM deposit d WHERE d.deposit_cart_id = c.cart_id) THEN 'deposit_only'
             ELSE 'no_document' END
    ) AS invoice_status,
    
    -- Receipt information
    r.receipt_id,
    
    -- Total paid amount from ALL payment sources
    COALESCE(
        -- Payments linked to invoice
        (SELECT SUM(p2.payment_amount) 
         FROM payment p2 
         WHERE p2.payment_invoice_id = i.invoice_id
         AND p2.payment_status = 'completed'),
         
        -- Payments linked to receipt
        (SELECT SUM(p3.payment_amount)
         FROM payment p3
         WHERE p3.payment_id = r.receipt_payment_id
         AND p3.payment_status = 'completed'),
         
        0
    ) AS total_paid,
    
    -- Total deposited amount (from deposits table)
    COALESCE(
        (SELECT SUM(d2.deposit_amount) 
         FROM deposit d2 
         WHERE (d2.deposit_cart_id = c.cart_id OR d2.deposit_invoice_id = i.invoice_id)
         AND d2.deposit_amount > 0), 
        0
    ) AS total_deposited,
    
    -- Balance due calculation (considering all payment types)
    COALESCE(i.invoice_total_amount, c.cart_total_amount, 0) - 
    (
        COALESCE(
            (SELECT SUM(p2.payment_amount) 
             FROM payment p2 
             WHERE p2.payment_invoice_id = i.invoice_id
             AND p2.payment_status = 'completed'), 0
        ) +
        COALESCE(
            (SELECT SUM(d2.deposit_amount) 
             FROM deposit d2 
             WHERE (d2.deposit_cart_id = c.cart_id OR d2.deposit_invoice_id = i.invoice_id)
             AND d2.deposit_amount > 0), 0
        )
    ) AS balance_due,
    
    -- Payment status (comprehensive)
    CASE 
        -- Receipt-based payments (immediate)
        WHEN r.receipt_id IS NOT NULL THEN 
            CASE WHEN r.receipt_amount >= COALESCE(c.cart_total_amount, 0) 
                 THEN 'fully_paid_receipt' 
                 ELSE 'partially_paid_receipt' 
            END
        
        -- Invoice-based payments
        WHEN i.invoice_id IS NOT NULL THEN
            CASE 
                WHEN EXISTS (
                    SELECT 1 FROM payment p3 
                    WHERE p3.payment_invoice_id = i.invoice_id 
                    AND p3.payment_status = 'completed'
                    AND p3.payment_amount >= i.invoice_total_amount
                ) THEN 'fully_paid_invoice'
                
                WHEN EXISTS (
                    SELECT 1 FROM deposit d3 
                    WHERE d3.deposit_invoice_id = i.invoice_id
                    AND d3.deposit_amount >= i.invoice_total_amount
                ) THEN 'fully_paid_deposit'
                
                WHEN EXISTS (
                    SELECT 1 FROM payment p4 
                    WHERE p4.payment_invoice_id = i.invoice_id 
                    AND p4.payment_status = 'completed'
                ) OR EXISTS (
                    SELECT 1 FROM deposit d4 
                    WHERE d4.deposit_invoice_id = i.invoice_id
                ) THEN 'partially_paid'
                
                ELSE 'unpaid_invoice'
            END
        
        -- Deposit-only (no invoice/receipt)
        WHEN EXISTS (SELECT 1 FROM deposit d5 WHERE d5.deposit_cart_id = c.cart_id) THEN
            CASE 
                WHEN (SELECT SUM(d6.deposit_amount) FROM deposit d6 
                      WHERE d6.deposit_cart_id = c.cart_id) >= COALESCE(c.cart_total_amount, 0)
                THEN 'fully_paid_deposit_only'
                ELSE 'partially_paid_deposit_only'
            END
        
        -- No financial documents yet
        ELSE 'pending_payment'
    END AS payment_status,
    
    -- Document type
    CASE 
        WHEN i.invoice_id IS NOT NULL AND r.receipt_id IS NOT NULL THEN 'invoice_and_receipt'
        WHEN i.invoice_id IS NOT NULL THEN 'invoice'
        WHEN r.receipt_id IS NOT NULL THEN 'receipt'
        WHEN EXISTS (SELECT 1 FROM deposit d WHERE d.deposit_cart_id = c.cart_id) THEN 'deposit_only'
        ELSE 'no_document'
    END AS document_type,
    
    -- Operation type
    CASE 
        WHEN EXISTS (SELECT 1 FROM ordered_item oi WHERE oi.ordered_item_cart_ref = c.cart_id) 
             AND EXISTS (SELECT 1 FROM ordered_service os WHERE os.ordered_service_cart_id = c.cart_id)
        THEN 'mixed_products_services'
        WHEN EXISTS (SELECT 1 FROM ordered_item oi WHERE oi.ordered_item_cart_ref = c.cart_id) 
        THEN 'products_only'
        WHEN EXISTS (SELECT 1 FROM ordered_service os WHERE os.ordered_service_cart_id = c.cart_id) 
        THEN 'services_only'
        ELSE 'empty_cart'
    END AS operation_type,
    
    -- Source identifier
    'cart_based' AS source_table,
    
    -- Creation timestamp
    COALESCE(
        i.invoice_created_at,
        r.receipt_created_at,
        c.cart_created_at
    ) AS operation_date

FROM cart c
-- Join to Product Provider (Supplier)
LEFT JOIN product_provider pp ON c.cart_product_provider_id = pp.id_product_provider
-- Join to Invoice (if exists)
LEFT JOIN invoice i ON c.cart_id = i.invoice_cart_id
-- Join to Receipt (if exists)
LEFT JOIN receipt r ON c.cart_id = r.receipt_cart_ref
-- Join to Placed Order (if exists - corrected relationship)
LEFT JOIN placed_order po ON po.placed_order_invoice_ref = i.invoice_id OR 
                            (po.id_placed_order IN (
                                SELECT oi.order_ref 
                                FROM ordered_item oi 
                                WHERE oi.ordered_item_cart_ref = c.cart_id
                            ))

WHERE c.cart_status IN ('completed', 'pending', 'processing')  -- Only relevant carts

UNION ALL

-- PART 2: Direct Order-based items (without cart reference)
SELECT 
    -- Supplier information
    COALESCE(
        -- From product's provider
        (SELECT pp2.id_product_provider 
         FROM product p2 
         JOIN product_provider pp2 ON p2.product_provider_id = pp2.id_product_provider
         WHERE p2.id_product = oi.ordered_product_id),
         
        0
    ) AS supplier_id,
    
    -- Order information
    oi.order_ref AS order_id,
    
    -- Cart information (null for these)
    NULL AS cart_id,
    
    -- Client information from placed_order
    po.ordering_user_id AS client_id,
    
    -- Seller information (default to ordering user if no seller)
    COALESCE(
        (SELECT au.id_app_user FROM app_user au 
         WHERE au.id_app_user IN (SELECT au2.id_app_user FROM app_user au2 WHERE au2.id_app_user = po.ordering_user_id)),
        po.ordering_user_id
    ) AS seller_id,
    
    -- Financial information
    (oi.ordered_quantity * oi.unit_price * 
     (1 - COALESCE(oi.product_discount, 0)/100) *
     (1 + COALESCE(oi.applied_vat, 0)/100)) AS total_amount,
    
    -- Invoice information
    i.invoice_id,
    COALESCE(i.invoice_status, 'no_invoice') AS invoice_status,
    
    -- Receipt information
    NULL AS receipt_id,
    
    -- Total paid amount
    COALESCE(
        (SELECT SUM(p2.payment_amount)
         FROM payment p2
         WHERE p2.payment_invoice_id = i.invoice_id
         AND p2.payment_status = 'completed'),
        0
    ) AS total_paid,
    
    -- Total deposited amount
    COALESCE(
        (SELECT SUM(d2.deposit_amount)
         FROM deposit d2
         WHERE d2.deposit_invoice_id = i.invoice_id),
        0
    ) AS total_deposited,
    
    -- Balance due
    (oi.ordered_quantity * oi.unit_price * 
     (1 - COALESCE(oi.product_discount, 0)/100) *
     (1 + COALESCE(oi.applied_vat, 0)/100)) - 
    COALESCE(
        (SELECT SUM(p2.payment_amount)
         FROM payment p2
         WHERE p2.payment_invoice_id = i.invoice_id
         AND p2.payment_status = 'completed'),
        0
    ) - 
    COALESCE(
        (SELECT SUM(d2.deposit_amount)
         FROM deposit d2
         WHERE d2.deposit_invoice_id = i.invoice_id),
        0
    ) AS balance_due,
    
    -- Payment status
    CASE 
        WHEN i.invoice_id IS NULL THEN 'no_invoice'
        
        WHEN EXISTS (
            SELECT 1 FROM payment p3 
            WHERE p3.payment_invoice_id = i.invoice_id 
            AND p3.payment_status = 'completed'
            AND p3.payment_amount >= i.invoice_total_amount
        ) THEN 'fully_paid'
        
        WHEN EXISTS (
            SELECT 1 FROM payment p3 
            WHERE p3.payment_invoice_id = i.invoice_id 
            AND p3.payment_status = 'completed'
        ) OR EXISTS (
            SELECT 1 FROM deposit d3 
            WHERE d3.deposit_invoice_id = i.invoice_id
        ) THEN 'partially_paid'
        
        ELSE 'unpaid'
    END AS payment_status,
    
    -- Document type
    CASE 
        WHEN i.invoice_id IS NOT NULL THEN 'invoice'
        ELSE 'no_document'
    END AS document_type,
    
    -- Operation type
    'direct_order' AS operation_type,
    
    -- Source identifier
    'order_based' AS source_table,
    
    -- Creation timestamp
    COALESCE(
        i.invoice_created_at,
        po.placed_order_creation
    ) AS operation_date

FROM ordered_item oi
-- Join to placed_order
LEFT JOIN placed_order po ON po.id_placed_order = oi.order_ref
-- Join to invoice via placed_order
LEFT JOIN invoice i ON i.invoice_id = po.placed_order_invoice_ref
-- Only include items without cart reference but with order reference
WHERE oi.ordered_item_cart_ref IS NULL 
AND oi.order_ref IS NOT NULL
AND oi.ordered_product_id IS NOT NULL

UNION ALL

-- PART 3: Services-only operations (from ordered_service through cart)
SELECT 
    -- Supplier information from cart's provider
    pp.id_product_provider AS supplier_id,
    
    -- Order information (services usually don't create placed_orders)
    NULL AS order_id,
    
    -- Cart information
    c.cart_id,
    
    -- Client information
    COALESCE(c.cart_client_user, c.cart_selling_user) AS client_id,
    
    -- Seller information
    COALESCE(c.cart_selling_user, c.cart_client_user) AS seller_id,
    
    -- Financial information (sum of all services in cart)
    COALESCE(
        (SELECT SUM(os.ordered_service_total_price)
         FROM ordered_service os
         WHERE os.ordered_service_cart_id = c.cart_id),
        c.cart_total_amount,
        0
    ) AS total_amount,
    
    -- Invoice information
    i.invoice_id,
    COALESCE(i.invoice_status, 'no_invoice') AS invoice_status,
    
    -- Receipt information
    r.receipt_id,
    
    -- Total paid amount
    COALESCE(
        (SELECT SUM(p2.payment_amount) 
         FROM payment p2 
         WHERE p2.payment_invoice_id = i.invoice_id
         AND p2.payment_status = 'completed'),
         
        (SELECT SUM(p3.payment_amount)
         FROM payment p3
         WHERE p3.payment_id = r.receipt_payment_id
         AND p3.payment_status = 'completed'),
         
        0
    ) AS total_paid,
    
    -- Total deposited amount
    COALESCE(
        (SELECT SUM(d2.deposit_amount) 
         FROM deposit d2 
         WHERE d2.deposit_cart_id = c.cart_id),
        0
    ) AS total_deposited,
    
    -- Balance due
    COALESCE(
        (SELECT SUM(os.ordered_service_total_price)
         FROM ordered_service os
         WHERE os.ordered_service_cart_id = c.cart_id),
        c.cart_total_amount,
        0
    ) - 
    (
        COALESCE(
            (SELECT SUM(p2.payment_amount) 
             FROM payment p2 
             WHERE p2.payment_invoice_id = i.invoice_id
             AND p2.payment_status = 'completed'), 0
        ) +
        COALESCE(
            (SELECT SUM(d2.deposit_amount) 
             FROM deposit d2 
             WHERE d2.deposit_cart_id = c.cart_id), 0
        )
    ) AS balance_due,
    
    -- Payment status (similar to cart-based)
    CASE 
        WHEN r.receipt_id IS NOT NULL THEN 'fully_paid_receipt'
        WHEN i.invoice_id IS NOT NULL THEN
            CASE 
                WHEN EXISTS (
                    SELECT 1 FROM payment p3 
                    WHERE p3.payment_invoice_id = i.invoice_id 
                    AND p3.payment_status = 'completed'
                    AND p3.payment_amount >= i.invoice_total_amount
                ) THEN 'fully_paid_invoice'
                WHEN EXISTS (
                    SELECT 1 FROM payment p4 
                    WHERE p4.payment_invoice_id = i.invoice_id 
                    AND p4.payment_status = 'completed'
                ) THEN 'partially_paid'
                ELSE 'unpaid_invoice'
            END
        WHEN EXISTS (SELECT 1 FROM deposit d5 WHERE d5.deposit_cart_id = c.cart_id) THEN
            CASE 
                WHEN (SELECT SUM(d6.deposit_amount) FROM deposit d6 
                      WHERE d6.deposit_cart_id = c.cart_id) >= 
                     COALESCE(c.cart_total_amount, 0)
                THEN 'fully_paid_deposit_only'
                ELSE 'partially_paid_deposit_only'
            END
        ELSE 'pending_payment'
    END AS payment_status,
    
    -- Document type
    CASE 
        WHEN i.invoice_id IS NOT NULL THEN 'invoice'
        WHEN r.receipt_id IS NOT NULL THEN 'receipt'
        WHEN EXISTS (SELECT 1 FROM deposit d WHERE d.deposit_cart_id = c.cart_id) THEN 'deposit_only'
        ELSE 'no_document'
    END AS document_type,
    
    -- Operation type
    'services_only' AS operation_type,
    
    -- Source identifier
    'service_based' AS source_table,
    
    -- Creation timestamp
    COALESCE(
        i.invoice_created_at,
        r.receipt_created_at,
        c.cart_created_at
    ) AS operation_date

FROM cart c
-- Join to Product Provider
LEFT JOIN product_provider pp ON c.cart_product_provider_id = pp.id_product_provider
-- Join to Invoice
LEFT JOIN invoice i ON c.cart_id = i.invoice_cart_id
-- Join to Receipt
LEFT JOIN receipt r ON c.cart_id = r.receipt_cart_ref
-- Ensure cart has services
WHERE EXISTS (SELECT 1 FROM ordered_service os WHERE os.ordered_service_cart_id = c.cart_id)
AND NOT EXISTS (SELECT 1 FROM ordered_item oi WHERE oi.ordered_item_cart_ref = c.cart_id)  -- No products
AND c.cart_status IN ('completed', 'pending', 'processing');





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
