-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 13:59:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gluttex` ;

-- -----------------------------------------------------
-- Schema gluttex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gluttex` DEFAULT CHARACTER SET utf8 ;
USE `gluttex` ;

-- -----------------------------------------------------
-- Table `gluttex`.`app_user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user_type` (
  `id_app_user_type` INT NOT NULL AUTO_INCREMENT,
  `app_user_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_app_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`person_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person_details` (
  `id_person_details` INT NOT NULL AUTO_INCREMENT,
  `person_first_name` VARCHAR(45) NULL,
  `person_last_name` VARCHAR(45) NULL,
  `person_birth_date` DATE NULL,
  `person_gender` VARCHAR(45) NULL,
  `person_nationality` VARCHAR(45) NULL,
  PRIMARY KEY (`id_person_details`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`blood_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`blood_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`blood_type` (
  `id_blood_type` INT NOT NULL AUTO_INCREMENT,
  `blood_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_blood_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`address` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(45) NULL,
  `address_city` VARCHAR(45) NULL,
  `address_postal_code` VARCHAR(45) NULL,
  `address_country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`location` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `location_latitude` DECIMAL(10,8) NULL,
  `location_longitude` DECIMAL(11,8) NULL,
  `location_name` VARCHAR(45) NULL,
  `location_address_id` INT NULL,
  PRIMARY KEY (`id_location`),
  INDEX `fk_location_1_idx` (`location_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_1`
    FOREIGN KEY (`location_address_id`)
    REFERENCES `gluttex`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`person` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `person_details_id` INT NULL,
  `person_blood_type_id` INT NULL,
  `person_location_id` INT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_1_idx` (`person_details_id` ASC) VISIBLE,
  INDEX `fk_person_2_idx` (`person_blood_type_id` ASC) VISIBLE,
  INDEX `fk_person_3_idx` (`person_location_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_1`
    FOREIGN KEY (`person_details_id`)
    REFERENCES `gluttex`.`person_details` (`id_person_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_2`
    FOREIGN KEY (`person_blood_type_id`)
    REFERENCES `gluttex`.`blood_type` (`id_blood_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_3`
    FOREIGN KEY (`person_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`app_user` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`app_user` (
  `id_app_user` INT NOT NULL AUTO_INCREMENT,
  `app_user_name` VARCHAR(100) NULL,
  `app_user_password` VARCHAR(256) NULL,
  `app_user_person_id` INT NULL,
  `app_user_type_id` INT NULL,
  `app_user_preferences` TEXT NULL,
  `app_user_image` BLOB NULL,
  `app_user_last_active` DATETIME NULL,
  `app_user_last_updated` DATETIME NULL,
  `app_user_creation` DATETIME NULL,
  PRIMARY KEY (`id_app_user`),
  INDEX `fk_app_user_3_idx` (`app_user_person_id` ASC) VISIBLE,
  INDEX `fk_app_user_1_idx` (`app_user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_app_user_1`
    FOREIGN KEY (`app_user_type_id`)
    REFERENCES `gluttex`.`app_user_type` (`id_app_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_user_3`
    FOREIGN KEY (`app_user_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_provider_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider_type` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider_type` (
  `id_product_provider_type` INT NOT NULL AUTO_INCREMENT,
  `product_provider_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product_provider_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_details` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_details` (
  `idprovider_details_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NULL,
  `provider_contact_info` TEXT NULL,
  PRIMARY KEY (`idprovider_details_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`provider_organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`provider_organisation` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`provider_organisation` (
  `idprovider_organisation` INT NOT NULL AUTO_INCREMENT,
  `provider_organisation_name` VARCHAR(45) NULL,
  `provider_organisation_desc` VARCHAR(300) NULL,
  PRIMARY KEY (`idprovider_organisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_provider` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_provider` (
  `id_product_provider` INT NOT NULL AUTO_INCREMENT,
  `product_provider_details_id` INT NULL,
  `product_provider_type_id` INT NULL,
  `product_provider_location_id` INT NULL,
  `product_provider_org_id` INT NULL,
  PRIMARY KEY (`id_product_provider`),
  INDEX `fk_product_provider_3_idx` (`product_provider_details_id` ASC) VISIBLE,
  INDEX `fk_product_provider_1_idx` (`product_provider_type_id` ASC) VISIBLE,
  INDEX `fk_product_provider_4_idx` (`product_provider_location_id` ASC) VISIBLE,
  INDEX `fk_product_provider_2_idx` (`product_provider_org_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_provider_1`
    FOREIGN KEY (`product_provider_type_id`)
    REFERENCES `gluttex`.`product_provider_type` (`id_product_provider_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider_3`
    FOREIGN KEY (`product_provider_details_id`)
    REFERENCES `gluttex`.`provider_details` (`idprovider_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider_4`
    FOREIGN KEY (`product_provider_location_id`)
    REFERENCES `gluttex`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider_2`
    FOREIGN KEY (`product_provider_org_id`)
    REFERENCES `gluttex`.`provider_organisation` (`idprovider_organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_category` (
  `id_product_category` INT NOT NULL AUTO_INCREMENT,
  `product_category_desc` VARCHAR(45) NULL,
  `product_category_icon` TEXT NULL,
  PRIMARY KEY (`id_product_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_brand` VARCHAR(45) NULL,
  `product_provider_id` INT NULL,
  `product_category_id` INT NULL,
  `product_barcode` VARCHAR(45) NULL,
  `last_updated` DATETIME NULL,
  `created` DATETIME NULL,
  `product_description` VARCHAR(300) NULL,
  `product_price` DOUBLE NULL,
  `product_quantity` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_product_1_idx` (`product_provider_id` ASC) VISIBLE,
  INDEX `fk_product_2_idx` (`product_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_1`
    FOREIGN KEY (`product_provider_id`)
    REFERENCES `gluttex`.`product_provider` (`id_product_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_2`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `gluttex`.`product_category` (`id_product_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`disease_severity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`disease_severity` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`disease_severity` (
  `id_disease_severity` INT NOT NULL AUTO_INCREMENT,
  `disease_severity_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_disease_severity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`patient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`patient` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `patient_person_id` INT NULL,
  `patient_disease_severity_id` INT NULL,
  PRIMARY KEY (`id_patient`),
  INDEX `fk_patient_1_idx` (`patient_person_id` ASC) VISIBLE,
  INDEX `fk_patient_2_idx` (`patient_disease_severity_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_1`
    FOREIGN KEY (`patient_person_id`)
    REFERENCES `gluttex`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_2`
    FOREIGN KEY (`patient_disease_severity_id`)
    REFERENCES `gluttex`.`disease_severity` (`id_disease_severity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`serology_indicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`serology_indicator` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`serology_indicator` (
  `id_serology_indicator` INT NOT NULL AUTO_INCREMENT,
  `serology_indicator_name` VARCHAR(45) NULL,
  `serology_indicator_desc` VARCHAR(300) NULL,
  PRIMARY KEY (`id_serology_indicator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`serology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`serology` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`serology` (
  `id_serology` INT NOT NULL AUTO_INCREMENT,
  `indicator_id` INT NULL,
  `serology_date` DATE NULL,
  `patient_id` INT NULL,
  `indicator_value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_serology`),
  INDEX `fk_diagnosis_1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_serology_1_idx` (`indicator_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosis_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `gluttex`.`patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serology_1`
    FOREIGN KEY (`indicator_id`)
    REFERENCES `gluttex`.`serology_indicator` (`id_serology_indicator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_category` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_category` (
  `id_recipe_category` INT NOT NULL AUTO_INCREMENT,
  `recipe_category_desc` VARCHAR(45) NULL,
  `recipe_category_icon` TEXT NULL,
  PRIMARY KEY (`id_recipe_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe` (
  `id_recipe` INT NOT NULL AUTO_INCREMENT,
  `recipe_owner_id` INT NULL,
  `recipe_category_id` INT NULL,
  `recipe_preparation_time` VARCHAR(45) NULL,
  `recipe_instructions` TEXT NULL,
  `recipe_name` VARCHAR(45) NULL,
  `recipe_description` VARCHAR(300) NULL,
  `recipe_creation` DATETIME NULL,
  `recipe_last_updated` DATETIME NULL,
  PRIMARY KEY (`id_recipe`),
  INDEX `fk_recipe_1_idx` (`recipe_owner_id` ASC) VISIBLE,
  INDEX `fk_recipe_2_idx` (`recipe_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_1`
    FOREIGN KEY (`recipe_owner_id`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_2`
    FOREIGN KEY (`recipe_category_id`)
    REFERENCES `gluttex`.`recipe_category` (`id_recipe_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`ingredient` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `ingredient_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_contains_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_contains_ingredient` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_contains_ingredient` (
  `idrecipe_contains_ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `containing_recipe_id` INT NULL,
  `contained_ingredient_id` INT NULL,
  `contained_quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecipe_contains_ingredient_id`),
  INDEX `fk_recipe_contains_ingredient_1_idx` (`containing_recipe_id` ASC) VISIBLE,
  INDEX `fk_recipe_contains_ingredient_2_idx` (`contained_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_contains_ingredient_1`
    FOREIGN KEY (`containing_recipe_id`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_contains_ingredient_2`
    FOREIGN KEY (`contained_ingredient_id`)
    REFERENCES `gluttex`.`ingredient` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`product_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`product_image` (
  `id_product_image` INT NOT NULL AUTO_INCREMENT,
  `product_image_data` BLOB NULL,
  `product_ref_id` INT NULL,
  PRIMARY KEY (`id_product_image`),
  INDEX `fk_product_image_1_idx` (`product_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_image_1`
    FOREIGN KEY (`product_ref_id`)
    REFERENCES `gluttex`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`recipe_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`recipe_image` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`recipe_image` (
  `id_recipe_image` INT NOT NULL AUTO_INCREMENT,
  `recipe_image_data` BLOB NULL,
  `recipe_ref_id` INT NULL,
  PRIMARY KEY (`id_recipe_image`),
  INDEX `fk_recipe_image_1_idx` (`recipe_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_image_1`
    FOREIGN KEY (`recipe_ref_id`)
    REFERENCES `gluttex`.`recipe` (`id_recipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`symptoms_occurence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`symptoms_occurence` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`symptoms_occurence` (
  `id_symptoms_occurence` INT NOT NULL AUTO_INCREMENT,
  `symptoms_occurence_submission_time` DATETIME NULL,
  `symptoms_occurence_reason` VARCHAR(300) NULL,
  `symptoms_occurence_since_reason` DATETIME NULL,
  `symptoms_occurence_ref_patient` INT NULL,
  PRIMARY KEY (`id_symptoms_occurence`),
  INDEX `fk_symptoms_causality_1_idx` (`symptoms_occurence_ref_patient` ASC) VISIBLE,
  CONSTRAINT `fk_symptoms_causality_1`
    FOREIGN KEY (`symptoms_occurence_ref_patient`)
    REFERENCES `gluttex`.`patient` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`symptom` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`symptom` (
  `id_symptom` INT NOT NULL AUTO_INCREMENT,
  `symptom_name` VARCHAR(45) NULL,
  `symptom_desc` VARCHAR(300) NULL,
  PRIMARY KEY (`id_symptom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`presented_symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`presented_symptom` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`presented_symptom` (
  `id_presented_symptom` INT NOT NULL AUTO_INCREMENT,
  `presented_symptom_ref_symptoms_occurence` INT NULL,
  `presented_symptom_ref_symptom` INT NULL,
  PRIMARY KEY (`id_presented_symptom`),
  INDEX `fk_presented_symptom_1_idx` (`presented_symptom_ref_symptom` ASC) VISIBLE,
  INDEX `fk_presented_symptom_2_idx` (`presented_symptom_ref_symptoms_occurence` ASC) VISIBLE,
  CONSTRAINT `fk_presented_symptom_1`
    FOREIGN KEY (`presented_symptom_ref_symptom`)
    REFERENCES `gluttex`.`symptom` (`id_symptom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presented_symptom_2`
    FOREIGN KEY (`presented_symptom_ref_symptoms_occurence`)
    REFERENCES `gluttex`.`symptoms_occurence` (`id_symptoms_occurence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gluttex`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gluttex`.`report` ;

CREATE TABLE IF NOT EXISTS `gluttex`.`report` (
  `id_report` INT NOT NULL AUTO_INCREMENT,
  `report_text` TEXT NULL,
  `report_owner` INT NULL,
  PRIMARY KEY (`id_report`),
  INDEX `fk_report_1_idx` (`report_owner` ASC) VISIBLE,
  CONSTRAINT `fk_report_1`
    FOREIGN KEY (`report_owner`)
    REFERENCES `gluttex`.`app_user` (`id_app_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





INSERT INTO `gluttex`.`app_user_type` ( `app_user_type_desc`) VALUES
( 'Client'),
( 'Admin'),
( 'Cooking chef');

INSERT INTO `gluttex`.`blood_type` ( `blood_type_desc`) VALUES
('O+'),
('A+'),
('B+'),
('AB+'),
('O-'),
('A-'),
('B-'),
('AB-');

INSERT INTO `gluttex`.`product_category` ( `product_category_desc`) VALUES
('Baked Goods'),
('Spreads'),
('Cereals'),
('Pasta'),
('Snacks'),
('Beverages'),
('Desserts');

INSERT INTO `gluttex`.`product_provider_type` ( `product_provider_type_desc`) VALUES
('Restaurant'),
('Bakery'),
('Factory'),
('Supermarket');


INSERT INTO `gluttex`.`recipe_category` ( `recipe_category_desc`) VALUES
("Appetizers & Snacks"),
("Soups & Stews"),
("Salads"),
("Main Courses"),
("Side Dishes"),
("Pasta & Noodles"),
("Casseroles"),
("Breakfast & Brunch"),
("Breads & Baking"),
("Desserts"),
("Drinks & Beverages"),
("Sauces & Condiments"),
("International Cuisine"),
("Healthy & Special Diets"),
("Holiday & Seasonal"),
("Kids & Family"),
("Slow Cooker & Instant Pot"),
("Quick & Easy"),
("One-Pan Recipes"),
("Grilling & BBQ");







-- INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
-- ('Smart Technologies', 'Phone: +213 609 1126074, Email: mjmhqzs@example.com'),
-- ('Eco Systems', 'Phone: +213 606 7668104, Email: fbkulvv@example.com'),
-- ('Smart Corporation', 'Phone: +213 675 9893109, Email: jkjkbvj@example.com'),
-- ('Health Industries', 'Phone: +213 604 3331217, Email: uxsjtfy@example.com'),
-- ('Tech Partners', 'Phone: +213 641 7681417, Email: lksfdtv@example.com'),
-- ('Green Enterprises', 'Phone: +213 627 6240490, Email: lcaleej@example.com'),
-- ('Green Consulting', 'Phone: +213 641 9897301, Email: yfpplzr@example.com'),
-- ('Smart Corporation', 'Phone: +213 611 5823312, Email: kbcxhps@example.com'),
-- ('Eco Partners', 'Phone: +213 640 4406431, Email: jqaeljx@example.com'),
-- ('Innovative Enterprises', 'Phone: +213 600 6854116, Email: aakgoqm@example.com'),
-- ('Global Solutions', 'Phone: +213 661 6236168, Email: unadtjk@example.com'),
-- ('Green Corporation', 'Phone: +213 653 3147806, Email: qrhkloy@example.com'),
-- ('Prime Technologies', 'Phone: +213 608 5803282, Email: mplnqpb@example.com'),
-- ('Innovative Corporation', 'Phone: +213 682 5387637, Email: ongcbmo@example.com'),
-- ('Prime Technologies', 'Phone: +213 635 4163080, Email: yvqcumv@example.com'),
-- ('Global Services', 'Phone: +213 667 6194095, Email: npxexni@example.com'),
-- ('Bright Solutions', 'Phone: +213 609 5237134, Email: rospbtg@example.com'),
-- ('Health Industries', 'Phone: +213 674 4584401, Email: iqqrnoz@example.com'),
-- ('Tech Consulting', 'Phone: +213 639 6918018, Email: mzgzxmy@example.com'),
-- ('Dynamic Technologies', 'Phone: +213 622 5664114, Email: nqhtvuh@example.com'),
-- ('Bright Solutions', 'Phone: +213 655 1527858, Email: eorfakx@example.com'),
-- ('Bright Solutions', 'Phone: +213 688 7400754, Email: vpltnqs@example.com'),
-- ('Prime Consulting', 'Phone: +213 611 3908501, Email: vcfjnyj@example.com'),
-- ('Prime Solutions', 'Phone: +213 690 5009291, Email: emdrlxj@example.com'),
-- ('Smart Technologies', 'Phone: +213 644 9988918, Email: zzpbmpp@example.com'),
-- ('Bright Industries', 'Phone: +213 684 3960601, Email: prieuim@example.com'),
-- ('Global Technologies', 'Phone: +213 638 7617405, Email: mrphlvv@example.com'),
-- ('Eco Consulting', 'Phone: +213 662 6706103, Email: khphupc@example.com'),
-- ('Green Partners', 'Phone: +213 635 9913502, Email: wlfnjcv@example.com'),
-- ('Global Consulting', 'Phone: +213 643 2839789, Email: upgoewx@example.com');




-- INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`) VALUES
-- ('31.4704', '10.5995','Algiers'),
-- ('21.9235', '6.6383','Oran'),
-- ('33.3383', '-0.7512','Constantine'),
-- ('30.3659', '11.3850','Annaba'),
-- ('31.2074', '8.0155','Blida'),
-- ('32.3339', '-0.0670','Batna'),
-- ('26.7321', '9.2440','Sétif'),
-- ('33.0055', '-5.9117','Tlemcen'),
-- ('30.2891', '2.5290','Biskra'),
-- ('29.1807', '3.8425','Béjaïa'),
-- ('26.1838', '-7.1486','Tizi Ouzou'),
-- ('32.5957', '-3.5024','Chlef'),
-- ('34.7306', '8.1922','Sidi Bel Abbès'),
-- ('31.0770', '-1.8179','Djelfa'),
-- ('26.7578', '11.0753','Guelma'),
-- ('28.5457', '-5.5282','Mascara'),
-- ('33.0417', '1.0216','Skikda'),
-- ('29.2655', '11.9160','Ouargla'),
-- ('33.7725', '1.0248','Relizane'),
-- ('27.2296', '-7.0964','Tiaret'),
-- ('36.0817', '9.7897','Tindouf'),
-- ('31.9784', '1.2928','Laghouat'),
-- ('30.6563', '2.6474','Tebessa'),
-- ('31.1872', '9.6848','Mostaganem'),
-- ('24.3694', '-8.1194','Bordj Bou Arreridj'),
-- ('19.3143', '2.7007','Boumerdès'),
-- ('26.6551', '-2.8732','Ain Temouchent'),
-- ('33.1827', '4.8710','Médéa'),
-- ('31.6452', '1.0392','El Oued'),
-- ('25.2283', '-0.0806','Khenchela');

-- Insert data into the address table
INSERT INTO `gluttex`.`address` (`address_street`, `address_city`, `address_country`)
VALUES
('Rue Lamameri Ali', 'Bouzareah', 'Algeria'),
('Avenue Houari Boumedien', 'Bordj El Bahri', 'Algeria'),
('Route de Dar El Beida', 'Bab Ezzouar', 'Algeria'),
('N63', 'Mahelma', 'Algeria'),
('Khraicia', 'Khraicia', 'Algeria'),
('Cheraga', 'Chéraga', 'Algeria');


-- Insertions for Amissan -gluten free-
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Amissan -gluten free-', 'Facebook: https://www.facebook.com/profile.php?id=100063573159141, Phone number: 0781 56 64 26');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.79664864280521', '3.00456923564612', 'Rue Lamameri Ali', 1);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(1,1,2);

-- Insertions for Magasin habibou sans gluten
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Magasin habibou sans gluten', 'Facebook: https://www.facebook.com/profile.php?id=100063549909208');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.79104995021719', '3.244388200045344', 'Avenue Houari Boumedien', 2);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(2,2,2);

-- Insertions for Uno
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Uno', 'Facebook: https://www.facebook.com/UNO.Hypermarche/, Instagram: https://www.instagram.com/uno_hypermarche/');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.71305045006746', '3.191942199815943', 'Route de Dar El Beida', 3);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(3,3,4);

-- Insertions for Superette université
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Superette université', 'N/A');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.68805559407475', '2.872905857188605', 'N63', 4);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(4,4,4);

-- Insertions for Corridors Shopping
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Corridors Shopping', 'N/A');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.6683827', '2.9833228', 'Khraicia', 5);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(5,5,1);

-- Insertions for Caramel sans gluten
INSERT INTO `gluttex`.`provider_details` (`provider_name`, `provider_contact_info`) VALUES
('Caramel sans gluten', 'N/A');
INSERT INTO `gluttex`.`location` (`location_latitude`,`location_longitude`, `location_name`, `location_address_id`) VALUES
('36.75573869999999', '2.9514329', 'Cheraga', 6);
INSERT INTO `gluttex`.`product_provider` (`product_provider_location_id`, `product_provider_details_id`,`product_provider_type_id`) VALUES
(6,6,4);


-- Insert data into person_details table
INSERT INTO gluttex.person_details 
    (person_first_name, person_last_name, person_birth_date, person_gender, person_nationality) 
VALUES 
    ('Some', 'One', '2003-01-01', 'Male', 'Algerian');

-- Get the ID of the newly inserted person_details

-- Insert data into person table
INSERT INTO gluttex.person 
    (person_details_id, person_blood_type_id, person_location_id) 
VALUES 
    (1, 1, 1); 

-- Insert data into app_user table
INSERT INTO gluttex.app_user 
    (app_user_name, app_user_password, app_user_person_id, app_user_type_id) 
VALUES 
    ('SomeOne', 'password', 1, 1); 


-- Baked Goods
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Grano\'Sac Raisin Cacahuetes', 'Grano\'Sac','Delicious gluten-free baked goods made with raisins and peanuts. Perfect for a nutritious snack.', 1, 1, '1234567890123', 5.99, 100, CURDATE(), CURDATE()),
('Butter Biscuits LEGER', 'LEGER','Light and crispy gluten-free butter biscuits, a guilt-free treat for any time of the day.', 1, 1, '1234567890124', 4.49, 150, CURDATE(), CURDATE()),
('Cookies', 'Home Bakery','Indulgent gluten-free cookies baked to perfection, a delightful blend of flavors in every bite.', 1, 1, '1234567890125', 3.99, 200, CURDATE(), CURDATE()),
('Gullon Cookies', 'Gullon','Classic gluten-free cookies from Gullon, a favorite snack for both kids and adults.', 1, 1, '1234567890126', 6.29, 120, CURDATE(), CURDATE());

-- Spreads
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Date Butter', 'NutriLife','A rich and creamy date butter, packed with nutrients and perfect for spreading on toast or crackers.', 1, 2, '1234567890127', 7.99, 80, CURDATE(), CURDATE()),
('CARAIBE Crème à Tartiner', 'CARAIBE','Decadent chocolate spread from CARAIBE, a luxurious treat for chocolate lovers.', 1, 2, '1234567890128', 8.49, 100, CURDATE(), CURDATE()),
('JUMPY Beurre De Cacahuète', 'JUMPY','Smooth and creamy peanut butter spread, a versatile ingredient for sandwiches, smoothies, and desserts.', 1, 2, '1234567890129', 5.79, 90, CURDATE(), CURDATE());

-- Cereals
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Semoule de pain', 'BioCereal','Organic gluten-free semolina, perfect for making bread, couscous, and various desserts.', 1, 3, '1234567890130', 3.99, 120, CURDATE(), CURDATE()),
('Flocons D\'avoine (fariné)', 'NatureLand','Finely ground gluten-free oat flakes, ideal for baking bread, cookies, and other baked goods.', 1, 3, '1234567890131', 6.49, 80, CURDATE(), CURDATE()),
('Flocons D\'avoine (petits)', 'Healthy Harvest','Whole gluten-free oat flakes, a nutritious addition to your breakfast bowl or baked treats.', 1, 3, '1234567890132', 4.99, 100, CURDATE(), CURDATE());







-- Pasta
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Farine à Pizza', 'Mama\'s Kitchen','Premium gluten-free pizza flour blend, perfect for making homemade pizzas with a crispy crust.', 1, 4, '1234567890133', 5.99, 150, CURDATE(), CURDATE()),
('COUDE Pâtes sans gluten', 'Italian Delight','Gluten-free elbow pasta, ideal for pasta salads, casseroles, and creamy pasta dishes.', 1, 4, '1234567890134', 4.49, 100, CURDATE(), CURDATE());

-- Snacks
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Grano\'Sac Raisin Cacahuetes', 'Grano\'Sac','Delicious gluten-free baked goods made with raisins and peanuts. Perfect for a nutritious snack.', 1, 5, '1234567890123', 5.99, 100, CURDATE(), CURDATE()),
('Cookies', 'Home Bakery','Indulgent gluten-free cookies baked to perfection, a delightful blend of flavors in every bite.', 1, 5, '1234567890125', 3.99, 200, CURDATE(), CURDATE()),
('Gullon Cookies', 'Gullon','Classic gluten-free cookies from Gullon, a favorite snack for both kids and adults.', 1, 5, '1234567890126', 6.29, 120, CURDATE(), CURDATE());

-- Desserts
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Confiture Delicia fruit', 'Delicia','Exquisite gluten-free fruit jam, bursting with natural flavors and sweetness.', 1, 7, '1234567890135', 7.99, 80, CURDATE(), CURDATE()),
('Confiture Ela fraise', 'Ela','Delightful strawberry jam, perfect for spreading on toast, biscuits, or pairing with cheese.', 1, 7, '1234567890136', 6.49, 90, CURDATE(), CURDATE()),
('Flan Vanille Nouara', 'Nouara','Creamy vanilla flan dessert, a classic indulgence that melts in your mouth with every spoonful.', 1, 7, '1234567890137', 8.99, 70, CURDATE(), CURDATE());

-- Beverages
INSERT INTO `gluttex`.`product` (`product_name`, `product_brand`,`product_description`, `product_provider_id`, `product_category_id`, `product_barcode`, `product_price`, `product_quantity`,`last_updated`,`created`) VALUES
('Chocolat en poudre', 'ChocoMelt','Rich and velvety chocolate powder, perfect for making hot chocolate drinks or adding to desserts.', 1, 6, '1234567890138', 9.49, 60, CURDATE(), CURDATE());


INSERT INTO `gluttex`.`recipe` 
(`recipe_owner_id`, `recipe_category_id`, `recipe_preparation_time`, `recipe_instructions`, `recipe_name`, `recipe_description`, `recipe_creation`, `recipe_last_updated`)
VALUES
(1, 1, '30 minutes', 'Step 1: Do this.\nStep 2: Do that.', 'Tasty Appetizer', 'A delicious appetizer to start your meal.', NOW(), NOW()),
(1, 2, '45 minutes', 'Step 1: Prepare ingredients.\nStep 2: Cook.', 'Hearty Soup', 'A warm and comforting soup.', NOW(), NOW()),
(1, 3, '20 minutes', 'Step 1: Chop vegetables.\nStep 2: Mix ingredients.', 'Fresh Salad', 'A fresh and healthy salad.', NOW(), NOW()),
(1, 4, '1 hour', 'Step 1: Marinate meat.\nStep 2: Grill.', 'Grilled Chicken', 'Juicy grilled chicken with herbs.', NOW(), NOW()),
(1, 5, '30 minutes', 'Step 1: Boil water.\nStep 2: Cook side dish.', 'Mashed Potatoes', 'Creamy mashed potatoes.', NOW(), NOW()),
(1, 6, '40 minutes', 'Step 1: Prepare pasta.\nStep 2: Cook sauce.', 'Spaghetti Bolognese', 'Classic Italian pasta dish.', NOW(), NOW()),
(1, 7, '1 hour 30 minutes', 'Step 1: Prepare casserole.\nStep 2: Bake.', 'Cheesy Casserole', 'Cheesy and delicious casserole.', NOW(), NOW()),
(1, 8, '25 minutes', 'Step 1: Mix ingredients.\nStep 2: Cook.', 'Pancakes', 'Fluffy and light pancakes.', NOW(), NOW()),
(1, 9, '3 hours', 'Step 1: Prepare dough.\nStep 2: Bake.', 'Sourdough Bread', 'Homemade sourdough bread.', NOW(), NOW()),
(1, 10, '1 hour 15 minutes', 'Step 1: Prepare ingredients.\nStep 2: Bake.', 'Chocolate Cake', 'Rich and moist chocolate cake.', NOW(), NOW());

INSERT INTO  `gluttex`.`disease_severity` (`disease_severity_desc`) VALUES
('Marsh 0'),
('Marsh 1'),
('Marsh 2'),
('Marsh 3'),
('Marsh 3a'),
('Marsh 3b'),
('Marsh 3c'),
('Marsh 4');

insert into `gluttex`.`patient` (`patient_person_id` ,`patient_disease_severity_id`) values 
(1,1);


INSERT INTO `gluttex`.`symptom` (symptom_name, symptom_desc) VALUES
('Abdominal Pain', 'Pain in the stomach area'),
('Bloating', 'Swelling of the abdomen'),
('Diarrhea', 'Frequent loose stools'),
('Constipation', 'Difficulty in bowel movements'),
('Fatigue', 'Extreme tiredness'),
('Weight Loss', 'Unintentional loss of weight'),
('Anemia', 'Low red blood cell count'),
('Osteoporosis', 'Weakening of the bones'),
('Dermatitis Herpetiformis', 'Skin rash with blisters'),
('Nausea', 'Feeling of sickness with an inclination to vomit'),
('Vomiting', 'Ejecting stomach contents through the mouth'),
('Flatulence', 'Excessive gas in the digestive tract'),
('Headache', 'Pain in the head'),
('Joint Pain', 'Pain in the joints'),
('Muscle Cramps', 'Involuntary muscle contractions'),
('Depression', 'Persistent feeling of sadness'),
('Anxiety', 'Feeling of worry or fear'),
('Mouth Ulcers', 'Sores in the mouth'),
('Tingling Sensation', 'Pins and needles feeling in limbs'),
('Neuropathy', 'Damage to the nerves causing weakness or pain'),
('Infertility', 'Inability to conceive children'),
('Bone Pain', 'Pain in the bones'),
('Acid Reflux', 'Burning sensation in the chest'),
('Indigestion', 'Discomfort in the stomach after eating'),
('Irritability', 'Easily annoyed or angered'),
('Short Stature', 'Below-average height for age'),
('Delayed Puberty', 'Late onset of puberty changes'),
('Dizziness', 'Feeling of unsteadiness or loss of balance'),
('Malabsorption', 'Inability to absorb nutrients properly'),
('Iron Deficiency', 'Lack of sufficient iron in the body'),
('Calcium Deficiency', 'Lack of sufficient calcium in the body'),
('3 Deficiency', 'Lack of sufficient vitamin D in the body'),
('Alopecia Areata', 'Patchy hair loss'),
('Night Blindness', 'Difficulty seeing in low light conditions'),
('Glossitis', 'Inflammation of the tongue'),
('Cheilitis', 'Inflammation of the lips'),
('Peripheral Edema', 'Swelling of the lower limbs'),
('Ataxia', 'Lack of muscle coordination'),
('Seizures', 'Uncontrolled electrical activity in the brain'),
('Brain Fog', 'Cognitive dysfunction or confusion'),
('Mood Swings', 'Frequent changes in mood'),
('Panic Attacks', 'Sudden periods of intense fear'),
('Hyperthyroidism', 'Overactive thyroid gland'),
('Hypothyroidism', 'Underactive thyroid gland'),
('Heart Palpitations', 'Irregular or rapid heartbeat'),
('Sleep Disorders', 'Problems with sleeping'),
('Chronic Fatigue Syndrome', 'Persistent and severe fatigue'),
('Fibromyalgia', 'Widespread muscle pain and tenderness'),
('Dry Mouth', 'Lack of saliva production'),
('Dry Eyes', 'Lack of tear production'),
('Sinusitis', 'Inflammation of the sinuses'),
('Asthma', 'Respiratory condition with difficulty breathing'),
('Arthritis', 'Inflammation of the joints'),
('Eczema', 'Inflammatory skin condition with itchy rash'),
('Psoriasis', 'Skin condition with red, scaly patches'),
('Lactose Intolerance', 'Inability to digest lactose'),
('Intestinal Obstruction', 'Blockage of the intestines'),
('Gallstones', 'Stones formed in the gallbladder'),
('Pancreatitis', 'Inflammation of the pancreas'),
('Irritable Bowel Syndrome', 'Digestive disorder causing pain and discomfort'),
('Crohn’s Disease', 'Chronic inflammatory bowel disease'),
('Ulcerative Colitis', 'Chronic inflammation of the colon'),
('Lymphoma', 'Cancer of the lymphatic system'),
('Esophageal Cancer', 'Cancer of the esophagus'),
('Liver Disease', 'Impaired liver function'),
('Kidney Disease', 'Impaired kidney function'),
('Gallbladder Disease', 'Impaired gallbladder function'),
('Cholecystitis', 'Inflammation of the gallbladder'),
('Hypoglycemia', 'Low blood sugar levels'),
('Hyperglycemia', 'High blood sugar levels'),
('Celiac Crisis', 'Severe malnutrition and electrolyte imbalance due to celiac disease'),
('Small Intestinal Bacterial Overgrowth', 'Excessive bacteria in the small intestine'),
('Leaky Gut Syndrome', 'Increased intestinal permeability'),
('Candida Overgrowth', 'Excessive growth of Candida yeast in the body'),
('Fructose Malabsorption', 'Inability to digest fructose properly'),
('Histamine Intolerance', 'Sensitivity to histamine in foods'),
('Food Allergies', 'Immune response to certain foods'),
('Autoimmune Hepatitis', 'Immune system attacks liver cells'),
('Primary Biliary Cirrhosis', 'Chronic disease of the bile ducts'),
('Primary Sclerosing Cholangitis', 'Chronic disease affecting bile ducts and liver'),
('Peripheral Neuropathy', 'Damage to the peripheral nerves'),
('Central Neuropathy', 'Damage to the central nerves'),
('Chronic Kidney Disease', 'Long-term kidney damage and dysfunction'),
('Reproductive Disorders', 'Issues with reproductive system function'),
('Malignant Tumors', 'Cancerous growths'),
('Benign Tumors', 'Non-cancerous growths'),
('Nutrient Deficiencies', 'Lack of essential nutrients in the body'),
('Autoimmune Thyroiditis', 'Immune system attacks the thyroid gland'),
('Sjögren’s Syndrome', 'Autoimmune disease affecting glands that produce moisture'),
('Raynaud’s Phenomenon', 'Decreased blood flow to fingers and toes'),
('Systemic Lupus Erythematosus', 'Autoimmune disease affecting multiple organs'),
('Multiple Sclerosis', 'Disease affecting brain and spinal cord'),
('Dermatomyositis', 'Inflammatory disease affecting muscles and skin'),
('Scleroderma', 'Chronic connective tissue disease'),
('Ankylosing Spondylitis', 'Inflammatory arthritis affecting the spine'),
('Rheumatoid Arthritis', 'Autoimmune disease affecting joints'),
('Polymyalgia Rheumatica', 'Inflammatory disorder causing muscle pain and stiffness'),
('Temporal Arteritis', 'Inflammation of the temporal arteries'),
('Interstitial Lung Disease', 'Group of lung disorders causing scarring'),
('Pulmonary Fibrosis', 'Scarring of the lung tissue'),
('Sarcoidosis', 'Inflammatory disease affecting multiple organs'),
('Eosinophilic Esophagitis', 'Allergic condition affecting the esophagus'),
('Gastroesophageal Reflux Disease', 'Chronic acid reflux disease'),
('Peptic Ulcers', 'Sores in the lining of the stomach or duodenum'),
('Celiac Disease', 'Autoimmune disorder affecting the small intestine');


INSERT INTO `gluttex`.`serology_indicator` (serology_indicator_name, serology_indicator_desc) VALUES
('Antibody Level', 'Measurement of specific antibodies present in the blood. Often used to assess immune response or autoimmune conditions.'),
('Hemoglobin', 'The amount of hemoglobin in the blood, measured in grams per deciliter (g/dL). 2 is a protein in red blood cells that carries oxygen.'),
('Vitamin D', 'Measurement of the level of 3 in the blood, important for bone health and immune function.'),
('CRP', 'C-reactive protein (CRP) levels indicate inflammation in the body. High levels can suggest infection or chronic inflammatory conditions.'),
('ESR', 'Erythrocyte sedimentation rate (ESR) is a blood test that can reveal inflammatory activity in the body.'),
('Liver Enzymes', 'Measurement of enzymes like ALT and AST in the blood to assess liver function.'),
('Thyroid Function', 'Assessment of thyroid hormones (T3, T4, TSH) to evaluate thyroid gland activity.'),
('Iron', 'Measurement of iron levels in the blood, important for diagnosing anemia and other conditions.'),
('Calcium', 'Measurement of calcium levels in the blood, important for bone health, muscle function, and nerve signaling.'),
('Glucose', 'Blood sugar levels, important for diagnosing and monitoring diabetes.'),
('Cholesterol', 'Measurement of cholesterol levels, including HDL and LDL, important for assessing cardiovascular risk.'),
('Triglycerides', 'Measurement of triglyceride levels in the blood, important for assessing cardiovascular risk.'),
('Ferritin', 'Measurement of ferritin levels, which indicate the amount of stored iron in the body.'),
('B12', 'Measurement of Vitamin B12 levels, important for nerve function and the production of red blood cells.'),
('Folate', 'Measurement of folate levels, important for DNA synthesis and repair, and red blood cell production.'),
('IgA', 'Measurement of Immunoglobulin A (IgA) levels, important for immune function, particularly in mucous membranes.'),
('IgG', 'Measurement of Immunoglobulin G (IgG) levels, the most common antibody in blood and other body fluids, crucial for fighting bacterial and viral infections.'),
('IgM', 'Measurement of Immunoglobulin M (IgM) levels, the first antibody produced in response to an infection.'),
('Platelets', 'Measurement of platelet count in the blood, important for blood clotting.'),
('WBC', 'White blood cell count, important for assessing immune function and detecting infections.'),
('RBC', 'Red blood cell count, important for diagnosing anemia and other blood disorders.'),
('Albumin', 'Measurement of albumin levels, a protein made by the liver, important for maintaining oncotic pressure and transporting hormones, vitamins, and drugs.'),
('Globulin', 'Measurement of globulin levels, important for immune function and protein transport in the blood.'),
('Alkaline Phosphatase', 'Measurement of alkaline phosphatase levels, an enzyme related to the bile ducts; high levels can indicate liver or bone disorders.'),
('Bilirubin', 'Measurement of bilirubin levels, important for assessing liver function and diagnosing jaundice.'),
('Electrolytes', 'Measurement of electrolyte levels, including sodium, potassium, chloride, and bicarbonate, important for maintaining fluid balance and nerve/muscle function.');


-- Dummy data insertions
INSERT INTO `gluttex`.`serology` (patient_id, indicator_id, indicator_value, serology_date) VALUES
(1, '1', 'High', '2024-01-10'),
(1, '2', '13.5 g/dL', '2024-01-10'),
(1, '3', '20 ng/mL', '2024-01-10'),
(1, '1', 'Moderate', '2024-03-15'),
(1, '2', '14.0 g/dL', '2024-03-15'),
(1, '3', '22 ng/mL', '2024-03-15'),
(1, '1', 'Low', '2024-02-20'),
(1, '2', '12.0 g/dL', '2024-02-20'),
(1, '3', '18 ng/mL', '2024-02-20'),
(1, '1', 'Low', '2024-05-18'),
(1, '2', '11.5 g/dL', '2024-05-18'),
(1, '3', '16 ng/mL', '2024-05-18'),
(1, '1', 'High', '2024-04-25'),
(1, '2', '14.2 g/dL', '2024-04-25'),
(1, '3', '25 ng/mL', '2024-04-25'),
(1, '1', 'High', '2024-06-05'),
(1, '2', '13.8 g/dL', '2024-06-05'),
(1, '3', '24 ng/mL', '2024-06-05'),
(1, '1', 'Moderate', '2024-01-30'),
(1, '2', '13.0 g/dL', '2024-01-30'),
(1, '3', '19 ng/mL', '2024-01-30'),
(1, '1', 'Moderate', '2024-03-10'),
(1, '2', '13.3 g/dL', '2024-03-10'),
(1, '3', '21 ng/mL', '2024-03-10'),
(1, '1', 'Low', '2024-02-12'),
(1, '2', '12.2 g/dL', '2024-02-12'),
(1, '3', '17 ng/mL', '2024-02-12'),
(1, '1', 'Low', '2024-04-20'),
(1, '2', '11.8 g/dL', '2024-04-20'),
(1, '3', '15 ng/mL', '2024-04-20');


INSERT INTO `gluttex`.`ingredient` (ingredient_name) VALUES
('Wheat'),
('Barley'),
('Rye'),
('Oats'),
('Corn'),
('Rice'),
('Soy'),
('Milk'),
('Egg'),
('Peanuts'),
('Tree Nuts'),
('Fish'),
('Shellfish'),
('Lentils'),
('Chickpeas'),
('Quinoa'),
('Buckwheat'),
('Almond'),
('Coconut'),
('Flaxseed'),
('Sunflower Seeds'),
('Pumpkin Seeds'),
('Sesame Seeds'),
('Chia Seeds'),
('Hemp Seeds'),
('Sorghum'),
('Teff'),
('Amaranth'),
('Millet'),
('Tapioca'),
('Potato'),
('Sweet Potato'),
('Yam'),
('Arrowroot'),
('Cassava'),
('Taro'),
('Sago'),
('Agar'),
('Gelatin'),
('Xanthan Gum'),
('Guar Gum'),
('Psyllium'),
('Carob'),
('Carrageenan'),
('Lupin'),
('Mustard'),
('Celery'),
('Coriander'),
('Fennel'),
('Cumin'),
('Turmeric'),
('Ginger'),
('Garlic'),
('Onion'),
('Leek'),
('Shallot'),
('Scallion'),
('Chive'),
('Parsley'),
('Cilantro'),
('Basil'),
('Oregano'),
('Thyme'),
('Rosemary'),
('Sage'),
('Mint'),
('Dill'),
('Bay Leaf'),
('Marjoram'),
('Tarragon'),
('Lemongrass'),
('Lavender'),
('Paprika'),
('Chili Pepper'),
('Black Pepper'),
('White Pepper'),
('Green Pepper'),
('Red Pepper'),
('Cayenne Pepper'),
('Habanero'),
('Jalapeno'),
('Serrano'),
('Poblano'),
('Chipotle'),
('Bell Pepper'),
('Banana Pepper'),
('Pimento'),
('Cinnamon'),
('Clove'),
('Nutmeg'),
('Mace'),
('Allspice'),
('Cardamom'),
('Vanilla'),
('Star Anise'),
('Fenugreek'),
('Saffron'),
('Sassafras'),
('Licorice'),
('Anise'),
('Caraway'),
('Dill Seed'),
('Poppy Seed'),
('Sesame Seed'),
('Fennel Seed'),
('Nigella Seed'),
('Coriander Seed'),
('Cumin Seed'),
('Mustard Seed'),
('Fenugreek Seed'),
('Celery Seed'),
('Hemp Seed'),
('Chia Seed'),
('Flax Seed'),
('Pumpkin Seed'),
('Sunflower Seed'),
('Grapeseed Oil'),
('Olive Oil'),
('Canola Oil'),
('Coconut Oil'),
('Palm Oil'),
('Soybean Oil'),
('Peanut Oil'),
('Sesame Oil'),
('Sunflower Oil'),
('Safflower Oil'),
('Corn Oil'),
('Cottonseed Oil'),
('Rapeseed Oil'),
('Rice Bran Oil'),
('Walnut Oil'),
('Avocado Oil'),
('Hazelnut Oil'),
('Macadamia Oil'),
('Pecan Oil'),
('Pistachio Oil'),
('Ghee'),
('Butter'),
('Margarine'),
('Lard'),
('Tallow'),
('Shortening'),
('Vegetable Oil'),
('Animal Fat'),
('Baking Powder'),
('Baking Soda'),
('Yeast'),
('Cream of Tartar'),
('Cornstarch'),
('Potato Starch'),
('Arrowroot Powder'),
('Tapioca Starch'),
('Rice Flour'),
('Almond Flour'),
('Coconut Flour'),
('Buckwheat Flour'),
('Chickpea Flour'),
('Sorghum Flour'),
('Teff Flour'),
('Amaranth Flour'),
('Millet Flour'),
('Oat Flour'),
('Quinoa Flour'),
('Cassava Flour'),
('Rye Flour'),
('Barley Flour'),
('Wheat Flour'),
('Whole Wheat Flour'),
('All-Purpose Flour'),
('Bread Flour'),
('Cake Flour'),
('Pastry Flour'),
('Self-Rising Flour'),
('Gluten-Free Flour');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


