---
- name: Deploy Gluttex Stack
  hosts: all
  become: yes
  vars:
    API_PORT: "{{ lookup('env', 'API_PORT') }}"
    SQL_SCHEMA: "{{ lookup('env', 'SQL_SCHEMA') }}"
    SQL_HOST: "{{ lookup('env', 'SQL_HOST') }}"
    SQL_DATABASE: "{{ lookup('env', 'SQL_DATABASE') }}"
    SQL_USER: "{{ lookup('env', 'SQL_USER') }}"
    SQL_ROOT_PASSWORD: "{{ lookup('env', 'SQL_ROOT_PASSWORD') }}"
    SQL_PORT: "{{ lookup('env', 'SQL_PORT') }}"
    GOOGLE_CLIENT_ID: "{{ lookup('env', 'GOOGLE_CLIENT_ID') }}"
    GOOGLE_CLIENT_SECRET: "{{ lookup('env', 'GOOGLE_CLIENT_SECRET') }}"
    FACEBOOK_CLIENT_ID: "{{ lookup('env', 'FACEBOOK_CLIENT_ID') }}"
    FACEBOOK_CLIENT_SECRET: "{{ lookup('env', 'FACEBOOK_CLIENT_SECRET') }}"
    INSTAGRAM_CLIENT_ID: "{{ lookup('env', 'INSTAGRAM_CLIENT_ID') }}"
    INSTAGRAM_CLIENT_SECRET: "{{ lookup('env', 'INSTAGRAM_CLIENT_SECRET') }}"
    SECRET_KEY: "{{ lookup('env', 'SECRET_KEY') }}"
    ALGORITHM: "{{ lookup('env', 'ALGORITHM') }}"
    AUTH_SERVER_NAME: "{{ lookup('env', 'AUTH_SERVER_NAME') }}"
    AUTH_PORT: "{{ lookup('env', 'AUTH_PORT') }}"
    AUTH_REGISTRATION_ENDPOINT: "{{ lookup('env', 'AUTH_REGISTRATION_ENDPOINT') }}"
    AUTH_LOGIN_ENDPOINT: "{{ lookup('env', 'AUTH_LOGIN_ENDPOINT') }}"
    AUTH_CHANGE_ENDPOINT: "{{ lookup('env', 'AUTH_CHANGE_ENDPOINT') }}"
    ACCESS_TOKEN_EXPIRE_MINUTES: "{{ lookup('env', 'ACCESS_TOKEN_EXPIRE_MINUTES') }}"

  tasks:
    - name: Ensure gluttex-net network exists
      docker_network:
        name: gluttex-net
        driver: bridge

    - name: Deploy gluttex-api container
      docker_container:
        name: gluttex-api
        hostname: gluttex-api
        image: omarzos/gluttex-api
        restart_policy: always
        env:
          API_PORT: "{{ API_PORT }}"
          SQL_SCHEMA: "{{ SQL_SCHEMA }}"
          SQL_HOST: "{{ SQL_HOST }}"
          SQL_DATABASE: "{{ SQL_DATABASE }}"
          SQL_USER: "{{ SQL_USER }}"
          SQL_PASSWORD: "{{ SQL_ROOT_PASSWORD }}"
          SQL_PORT: "{{ SQL_PORT }}"
          API_GOOGLE_CLIENT_ID: "{{ GOOGLE_CLIENT_ID }}"
          API_GOOGLE_CLIENT_SECRET: "{{ GOOGLE_CLIENT_SECRET }}"
          API_FACEBOOK_CLIENT_ID: "{{ FACEBOOK_CLIENT_ID }}"
          API_FACEBOOK_CLIENT_SECRET: "{{ FACEBOOK_CLIENT_SECRET }}"
          API_INSTAGRAM_CLIENT_ID: "{{ INSTAGRAM_CLIENT_ID }}"
          API_INSTAGRAM_CLIENT_SECRET: "{{ INSTAGRAM_CLIENT_SECRET }}"
          API_SECRET_KEY: "{{ SECRET_KEY }}"
          ALGORITHM: "{{ ALGORITHM }}"
          AUTH_SERVER_NAME: "{{ AUTH_SERVER_NAME }}"
          AUTH_PORT: "{{ AUTH_PORT }}"
          AUTH_REGISTRATION_ENDPOINT: "{{ AUTH_REGISTRATION_ENDPOINT }}"
          AUTH_LOGIN_ENDPOINT: "{{ AUTH_LOGIN_ENDPOINT }}"
          AUTH_CHANGE_ENDPOINT: "{{ AUTH_CHANGE_ENDPOINT }}"
        ports:
          - "{{ API_PORT }}:{{ API_PORT }}"
        volumes:
          - ./server/:/code
        networks:
          - name: gluttex-net
        labels:
          traefik.enable: "true"
          traefik.http.routers.gluttex-api.rule: "Host(`gluttex.com`) && PathPrefix(`/`)"
          traefik.http.services.gluttex-api.loadbalancer.server.port: "9000"

    - name: Deploy gluttex-auth container
      docker_container:
        name: gluttex-auth
        hostname: gluttex-auth
        image: omarzos/gluttex-auth
        restart_policy: always
        env:
          ACCESS_TOKEN_EXPIRE_MINUTES: "{{ ACCESS_TOKEN_EXPIRE_MINUTES }}"
          AUTH_PORT: "{{ AUTH_PORT }}"
          API_SECRET_KEY: "{{ SECRET_KEY }}"
          API_ALGORITHM: "{{ ALGORITHM }}"
        ports:
          - "{{ AUTH_PORT }}:{{ AUTH_PORT }}"
        volumes:
          - ./auth_server/:/code
          - ./auth_server/auth_db/auth_db.db:/auth_db_data.db
        networks:
          - name: gluttex-net
        labels:
          traefik.enable: "true"
          traefik.http.routers.gluttex-auth.rule: "Host(`gluttex.com`) && PathPrefix(`/`)"
          traefik.http.services.gluttex-auth.loadbalancer.server.port: "9090"

    - name: Deploy Traefik container
      docker_container:
        name: traefik
        image: traefik:v2.10
        restart_policy: always
        command:
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--entrypoints.web.address=:80"
        ports:
          - "80:80"
          - "8080:8080"
        networks:
          - name: gluttex-net
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        labels:
          traefik.enable: "true"