


# -*- coding: utf-8 -*-
"""Celiac_Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AD5K_vkNmvV377P-HiEvnFLGBUM9HRJH

#**Project Statement**





##***Project Scope and Aim***



The current project aims to investigating pertinent  features that affects Celiac Health Risk predicting whether or not a patient is more likely to have Celiac disease.





The dataset used contains 14 features and 2206 records.

##***The medical variables used:***

- **Age**
- **Gender**
- **Diabetes:** yes, no
- **Diabetes Type:** Type 1, Type 2, none
- **Diarrhoea:** fatty, watery, inflammatory
- **Abdominal:** yes, no
- **Short Stature:**PSS, Variant, DSS
- **Sticky Stool:** yes, no
- **Weight Loss:** yes, no
- **Marsh:**indicates level of number of lymphocytes among cells on the surface of the intestinal lining: IELs (IntraEpithelial Lymphocytes): marsh type 0, marsh type 3a, marsh type 1, marsh type 2, marsh type 3b, none, marsh type 3c
- **cd_type:** potential, atypical, latent, silent, typical, none


The antibodies:
- **IgA**
- **IgG**
- **IgM**

#**Project Approach**


We aim to predict how likely is a patient to have Celiac disease based on the previously seen features (Binary Classification).




#***1- A first look at Celiac Health Risk Dataset***

1.   ***Data Understanding***
2.   ***Data Preprocessing***
    * Handling Missing Values
    * Hot Encoding
    * Dataset Balancing


#***2-  Model Implementation***

1.    ***Random Forest***
2.    ***GridSearchCV for parameter fine-tunning***
3.    ***Feature Importance***



#***3- Model Testing***


#***4- Deployment***

#***5- Conclusions***





***Dataset reference:***
https://www.kaggle.com/datasets/jackwin07/celiac-disease-coeliac-disease/data

#**1- A first look at Celiac Health Risks Dataset**

## Library Imports
This cell imports various libraries necessary for data handling, model building, and data visualization.
"""

# !pip install anvil-uplink

# import anvil.server
import pandas as pd
import numpy as np
import seaborn as sns
# import plotly.express as px
# import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# # anvil.server.connect("server_TUPLFHUNTRICV77Z7FBODVYC-ER3ZUKXV37PYOITA")

# """#**1.1 Data Understanding**

# """

# original_data = pd.read_csv('celiac_disease_lab_data.csv', sep=',', header=0)

# original_data.shape

# original_data.head(5)

# original_data.dtypes

# # what are the types of values in the field

# print('Gender values are: ', original_data['Gender'].unique())
# print('Diabetes values are', original_data['Diabetes'].unique())
# print('Diabetes Type values are', original_data['Diabetes Type'].unique())
# print('Diarrhoea values are: ', original_data['Diarrhoea'].unique())
# print('Abdominal values are', original_data['Abdominal'].unique())
# print('Short_Stature values are: ', original_data['Short_Stature'].unique())
# print('Sticky_Stool values are: ', original_data['Sticky_Stool'].unique())
# print('Weight_loss values are: ', original_data['Weight_loss'].unique())
# print('Marsh values are: ', original_data['Marsh'].unique())
# print('cd_type values are: ', original_data['cd_type'].unique())
# print('Disease_Diagnose values are: ', original_data['Disease_Diagnose'].unique())

# #how many null values are there
# original_data.isnull().sum()

# # check for data balancy
# original_data['Disease_Diagnose'].value_counts()

# sns.countplot(original_data['Disease_Diagnose'])

# """We notice that the dataset is imbalanced, it has to be balaneced!

# #**1.2 Data Preprocessing**

# #**1.2.1 Handling Missing Value**
# """

# original_data = original_data.fillna('none')

# original_data.isnull().sum()

# """
# #**1.2.2 Hot Encoding**
# """

# # Label Encoding for non-binary categorical variables
# label_encoders = {}
# for column in original_data.columns:
#     if original_data[column].dtype == 'object':
#         label_encoders[column] = LabelEncoder()
#         original_data[column] = label_encoders[column].fit_transform(original_data[column])

# original_data.dtypes

# print('Gender values are: ', original_data['Gender'].unique())
# print('Diabetes values are', original_data['Diabetes'].unique())
# print('Diabetes Type values are', original_data['Diabetes Type'].unique())
# print('Diarrhoea values are: ', original_data['Diarrhoea'].unique())
# print('Abdominal values are', original_data['Abdominal'].unique())
# print('Short_Stature values are: ', original_data['Short_Stature'].unique())
# print('Sticky_Stool values are: ', original_data['Sticky_Stool'].unique())
# print('Weight_loss values are: ', original_data['Weight_loss'].unique())
# print('Marsh values are: ', original_data['Marsh'].unique())
# print('cd_type values are: ', original_data['cd_type'].unique())
# print('Disease_Diagnose values are: ', original_data['Disease_Diagnose'].unique())

# for column_name, label_encoder in label_encoders.items():
#     print(f"Column: {column_name}")
#     numerical_labels = label_encoder.transform(label_encoder.classes_)
#     original_values = label_encoder.inverse_transform(numerical_labels)
#     for label, value in zip(numerical_labels, original_values):
#         print(f"Numerical Label: {label}, Original Value: {value}")
#     print()

# # Calculate the correlation between the target column 'Disease_Diagnose' and all other numeric features
# original_data.corr()['Disease_Diagnose'].sort_values()

# """#**1.2.3 Balancing Dataset**


# The positive Celiac cases are five times the number of the Negative Celiac cases. Building a model on such imbalanced dataset produces biased results, hence, it's of supreme importance to balance the dataset for good model performance.

# ***Balancing Our Datast: Upsampling***
# """

# #original_data['Disease_Diagnose'].value_counts()

# df_majority = original_data[(original_data['Disease_Diagnose']==1)]
# df_minority = original_data[(original_data['Disease_Diagnose']==0)]

# df_minority.shape

# # upsample minority class
# df_minority_upsampled = resample(df_minority,
#                                  replace=True,    # sample with replacement
#                                  n_samples= 1843, # to match majority class
#                                  random_state=42)  # reproducible results

# df_minority_upsampled.shape

# # Combine majority class with upsampled minority class
# df_upsampled = pd.concat([df_minority_upsampled, df_majority])

# df_upsampled['Disease_Diagnose'].value_counts()

# df_upsampled.head(5)

# """#***2- Modeling Using Random Forest***

# # ***2.1 Grid Search Methodology***
# - Systematic exploration of multiple hyperparameter combinations.
# - Identifies optimal values through exhaustive search.

# ## Data Splitting
# This cell splits the dataset into training and testing sets to evaluate the model's performance.


# *   Training_valdiation set 70% of data.
# *   Test set 30% of data.
# """

# X = df_upsampled.drop(columns=['Disease_Diagnose'])
# y = df_upsampled['Disease_Diagnose']

# # Splitting the dataset into train and test sets with a 70-30 ratio
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# # check for data balancy (y_train)
# y_train.value_counts()

# print ("X_train :", X_train.shape )
# print ("y_train :", y_train.shape )

# param_grid = {
#     'n_estimators': [5 ],  # the number of trees in the forest
#     'max_depth': [10],  # the maximum depth of each tree is usually 0 to avoid overfitting
#     'max_features': ['sqrt'],  # the number of features to consider at each split
#     'min_samples_split': [50],  # the minimum number of samples required to split a node
#     'min_samples_leaf': [50],  # the minimum number of samples required to be at a leaf node
#     'bootstrap': [True, False],  # whether to use bootstrap samples when building trees
#     'criterion': ['gini', 'entropy'],  # the function to measure the quality of a split
# }

# """## Setting Up Grid Search for Decision Tree

# Initializes a `DecisionTreeClassifier` and configures `GridSearchCV` with:
# - The decision tree classifier (`clf`) as the estimator.
# - A parameter grid (`param_grid`) to explore.
# - 4-fold cross-validation (`cv=4`).
# - f1 score as the scoring metric.
# - Try to change the scoring metric.
# """

# # Create an instance of the RandomForestClassifier class
rf = RandomForestClassifier()

# # Create an instance of the GridSearchCV class
# grid_search_rf = GridSearchCV(estimator= rf ,
#                               param_grid= param_grid,
#                               cv=4,
#                               scoring='f1',
#                               n_jobs=-1,
#                               verbose=2)

# """#***3- Model Testing***

# ## Executing Grid Search

# Runs `grid_search.fit` on the training data (`X_train`, `y_train`) to find the optimal hyperparameter settings based on the defined grid.
# """

# # Fit the grid search object to the data
# grid_search_rf.fit(X_train, y_train)

# """## Retrieving Best Model Parameters from Grid Search

# - Extracts `best_params` from `grid_search`, revealing the optimal hyperparameter settings.
# - Assigns `best_model` as the best estimator found by grid search.
# - Prints `best_params` to display the selected hyperparameters for the best model.
# """

# # Best RF parameters:
# best_model_rf = grid_search_rf.best_estimator_

# best_params_rf = grid_search_rf.best_params_
# print("Best RF parameters:", best_params_rf)

# # Predict on test set
# y_pred = grid_search_rf.best_estimator_.predict(X_test)

# # Concatenate X_train and y_train
# train_data = pd.concat([X_train, y_train], axis=1)

# # Concatenate X_test and y_test
# test_data = pd.concat([X_test, y_test], axis=1)

# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)


# # Generate a confusion matrix
# cm = confusion_matrix(y_test, y_pred)
# print("\nConfusion matrix: \n", cm)

# # Generate a classification report
# cr = classification_report(y_test, y_pred)
# print("\n Classification report: \n", cr)

# """#***- Correlation***"""

# # Calculate correlation matrix
# correlation_matrix = train_data.corr()

# # Extract correlation of features with the target variable (excluding target variable itself)
# target_correlation = correlation_matrix.iloc[:-1, -1]

# # Print the correlation of all features with the target variable
# target_correlation_sorted = target_correlation.sort_values()
# target_correlation_sorted

# # width, height
# # plt.figure(figsize=(14,10))
# sns.heatmap(df_upsampled.corr(), annot=True)

# # @anvil.server.callable
# from sklearn.preprocessing import LabelEncoder

def make_diagnosis(age, gender, diabetes, diabetes_type, diarroea, abdominal, short_stature, sticky_stool, weight_loss, IgA, IgG, IgM, marsh_type, cd_type, label_encoders=None):
    if label_encoders is None:
        label_encoders = {}

    # Define label encoders if not provided
    if 'gender' not in label_encoders:
        label_encoders['gender'] = LabelEncoder()
        label_encoders['gender'].fit(['Female', 'Male'])
    if 'diabetes' not in label_encoders:
        label_encoders['diabetes'] = LabelEncoder()
        label_encoders['diabetes'].fit(['Yes', 'no'])
    if 'diabetes_type' not in label_encoders:
        label_encoders['diabetes_type'] = LabelEncoder()
        label_encoders['diabetes_type'].fit(['Type 1', 'Type 2', 'none'])
    if 'diarroea' not in label_encoders:
        label_encoders['diarroea'] = LabelEncoder()
        label_encoders['diarroea'].fit(['fatty', 'inflammatory', 'watery'])
    if 'abdominal' not in label_encoders:
        label_encoders['abdominal'] = LabelEncoder()
        label_encoders['abdominal'].fit(['no', 'yes'])
    if 'short_stature' not in label_encoders:
        label_encoders['short_stature'] = LabelEncoder()
        label_encoders['short_stature'].fit(['DSS', 'PSS', 'Variant'])
    if 'sticky_stool' not in label_encoders:
        label_encoders['sticky_stool'] = LabelEncoder()
        label_encoders['sticky_stool'].fit(['no', 'yes'])
    if 'weight_loss' not in label_encoders:
        label_encoders['weight_loss'] = LabelEncoder()
        label_encoders['weight_loss'].fit(['no', 'yes'])
    if 'marsh_type' not in label_encoders:
        label_encoders['marsh_type'] = LabelEncoder()
        label_encoders['marsh_type'].fit(['marsh type 0', 'marsh type 1', 'marsh type 2', 'marsh type 3a', 'marsh type 3b', 'marsh type 3c', 'none'])
    if 'cd_type' not in label_encoders:
        label_encoders['cd_type'] = LabelEncoder()
        label_encoders['cd_type'].fit(['atypical', 'latent', 'none', 'potential', 'silent', 'typical'])

    # Encode categorical features
    encoded_gender = label_encoders['gender'].transform([gender])[0]
    encoded_diabetes = label_encoders['diabetes'].transform([diabetes])[0]
    encoded_diabetes_type = label_encoders['diabetes_type'].transform([diabetes_type])[0]
    encoded_diarroea = label_encoders['diarroea'].transform([diarroea])[0]
    encoded_abdominal = label_encoders['abdominal'].transform([abdominal])[0]
    encoded_short_stature = label_encoders['short_stature'].transform([short_stature])[0]
    encoded_sticky_stool = label_encoders['sticky_stool'].transform([sticky_stool])[0]
    encoded_weight_loss = label_encoders['weight_loss'].transform([weight_loss])[0]
    encoded_marsh_type = label_encoders['marsh_type'].transform([marsh_type])[0]
    encoded_cd_type = label_encoders['cd_type'].transform([cd_type])[0]
    classification = rf.predict([age, gender, diabetes, diabetes_type, diarroea, abdominal, short_stature, sticky_stool, weight_loss, IgA, IgG, IgM, marsh_type, cd_type])
    return classification

# anvil.server.wait_forever()

