

import os


# # getting a list of scylla node names ["node1","node2"]
# SCYLLA_NODES = os.getenv("SCYLLA_NODES").split(",")
# SCYLLA_KEYSPACE = os.getenv("SCYLLA_DEFAULT_KEYSPACE")


SQL_SCHEMA = os.getenv("SQL_SCHEMA","mysql+pymysql")
SQL_HOST = os.getenv("SQL_HOST","172.18.0.2")
SQL_USER = os.getenv("SQL_USER","root")
SQL_PASSWORD = os.getenv("SQL_PASSWORD","dev_password")
SQL_DATABASE = os.getenv("SQL_DATABASE","gluttex")
SQL_PORT= os.getenv("SQL_PORT","3306")
DB_URI = f"{SQL_SCHEMA}://{SQL_USER}:{SQL_PASSWORD}@{SQL_HOST}:{SQL_PORT}/{SQL_DATABASE}"


GOOGLE_CLIENT_ID = os.getenv("API_GOOGLE_CLIENT_ID",'')
GOOGLE_CLIENT_SECRET = os.getenv("API_GOOGLE_CLIENT_SECRET",'')
FACEBOOK_CLIENT_ID = os.getenv("API_FACEBOOK_CLIENT_ID",'')
FACEBOOK_CLIENT_SECRET = os.getenv("API_FACEBOOK_CLIENT_SECRET",'')
INSTAGRAM_CLIENT_ID = os.getenv("API_INSTAGRAM_CLIENT_ID",'')
INSTAGRAM_CLIENT_SECRET = os.getenv("API_INSTAGRAM_CLIENT_SECRET",'')

SECRET_KEY = os.getenv("API_SECRET_KEY",'')
ALGORITHM = os.getenv("ALGORITHM",'')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES",'')


AUTH_SERVER_NAME = os.getenv("AUTH_SERVER_NAME",'')
AUTH_PORT = os.getenv("AUTH_PORT",9090)
AUTH_REGISTRATION_ENDPOINT = os.getenv("AUTH_REGISTRATION_ENDPOINT",'')
AUTH_LOGIN_ENDPOINT = os.getenv("AUTH_LOGIN_ENDPOINT",'')
AUTH_CHANGE_ENDPOINT = os.getenv("AUTH_CHANGE_ENDPOINT",'')


FILE_UPLOAD_ENDPOINT= os.getenv("FILE_UPLOAD_ENDPOINT",'')
FS_HOST= os.getenv("FS_HOST",'')
FS_PORT= os.getenv("FS_PORT",'')



# COMPUTING_SERVER_BASE_URL = os.getenv("COMPUTING_SERVER_BASE_URL","gluttex") 


