FROM python:3.11-alpine

WORKDIR /code
COPY requirements.txt /

RUN apk add --no-cache \
    build-base \
    python3-dev \
    pango \
    cairo \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    glib-dev \
    freetype-dev \
    fontconfig-dev \
    jpeg-dev \
    openjpeg-dev \
    tiff-dev \
    libwebp-dev \
    && pip install --no-cache-dir pillow


# RUN pip install  --upgrade pip

COPY certificates/auth_cert.pem /usr/local/share/ca-certificates
RUN update-ca-certificates

RUN pip3 install -r /requirements.txt
# CMD ["sh", "-c", "uvicorn server:app --host 0.0.0.0 --port ${API_PORT}"]
